-- CreateTable
CREATE TABLE `warehouse_stock_movement_archive` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ITEM_ID` INTEGER NOT NULL,
    `ITEM_CODE` VARCHAR(191) NOT NULL,
    `ITEM_NAME` VARCHAR(191) NOT NULL,
    `WAREHOUSE_ID` INTEGER NOT NULL,
    `WAREHOUSE_NAME` VARCHAR(191) NOT NULL,
    `PREVIOUS_AVAILABLE_QUANTITY` DECIMAL(15, 4) NOT NULL,
    `PREVIOUS_ON_HAND_QUANTITY` DECIMAL(15, 4) NOT NULL,
    `AVAILABLE_QUANTITY_DELTA` DECIMAL(15, 4) NOT NULL,
    `ON_HAND_QUANTITY_DELTA` DECIMAL(15, 4) NOT NULL,
    `MOVEMENT_TYPE` VARCHAR(191) NOT NULL,
    `DOCUMENT_ID` INTEGER NOT NULL,
    `DOCUMENT_TYPE` VARCHAR(191) NOT NULL,
    `REASON` VARCHAR(191) NOT NULL,
    `REMARK` VARCHAR(191) NOT NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `warehouse_stock_movement_archive_ITEM_ID_CREATED_AT_idx`(`ITEM_ID`, `CREATED_AT`),
    INDEX `warehouse_stock_movement_archive_WAREHOUSE_ID_idx`(`WAREHOUSE_ID`),
    INDEX `warehouse_stock_movement_archive_MOVEMENT_TYPE_idx`(`MOVEMENT_TYPE`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
