-- Operating-cost / expense module (Pro-only). See
-- docs/future/EXPENSE_AND_CASH_RECONCILIATION.md §7 and docs/modules/EXPENSE.md.
-- Two greenfield tenant-scoped tables. Additive only — no existing table is
-- touched, so this is safe on prod (backup_db_prod runs first per policy).

-- CreateTable
CREATE TABLE `expense_category` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `KIND` VARCHAR(191) NOT NULL DEFAULT 'opex',
    `VERTICAL` VARCHAR(191) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `expense_category_CREATED_AT_UPDATED_AT_DELETED_AT_idx`(`CREATED_AT`, `UPDATED_AT`, `DELETED_AT`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `expense` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `OUTLET_ID` INTEGER NOT NULL DEFAULT 1,
    `SESSION_ID` INTEGER NULL,
    `EXPENSE_CATEGORY_ID` INTEGER NOT NULL,
    `CADENCE` VARCHAR(191) NOT NULL DEFAULT 'oneoff',
    `AMOUNT` DECIMAL(15, 4) NOT NULL,
    `BUSINESS_DATE` DATETIME(3) NOT NULL,
    `PERIOD_MONTH` VARCHAR(191) NULL,
    `NOTE` VARCHAR(191) NULL DEFAULT '',
    `PAYMENT_SOURCE` VARCHAR(191) NOT NULL DEFAULT 'cash',
    `RECURRING_TEMPLATE_ID` INTEGER NULL,
    `SOURCE_MOVEMENT_ID` INTEGER NULL,
    `RECEIPT_URL` VARCHAR(191) NULL,
    `PERFORMED_BY` INTEGER NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `expense_OUTLET_ID_BUSINESS_DATE_idx`(`OUTLET_ID`, `BUSINESS_DATE`),
    INDEX `expense_SESSION_ID_idx`(`SESSION_ID`),
    INDEX `expense_UPDATED_AT_idx`(`UPDATED_AT`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `expense` ADD CONSTRAINT `expense_EXPENSE_CATEGORY_ID_fkey` FOREIGN KEY (`EXPENSE_CATEGORY_ID`) REFERENCES `expense_category`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
