-- CreateTable
CREATE TABLE `app_version` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PLATFORM` VARCHAR(191) NOT NULL,
    `MIN_VERSION` VARCHAR(191) NOT NULL,
    `LATEST_VERSION` VARCHAR(191) NOT NULL,
    `TITLE` VARCHAR(191) NULL,
    `MESSAGE` VARCHAR(191) NULL,
    `STORE_URL` VARCHAR(191) NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    UNIQUE INDEX `app_version_PLATFORM_key`(`PLATFORM`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
