/*
  Warnings:

  - You are about to drop the column `BUSINESS_DATE` on the `DECLARATION` table. All the data in the column will be lost.
  - You are about to drop the column `CLOSED_BY` on the `DECLARATION` table. All the data in the column will be lost.
  - You are about to drop the column `CLOSING_DATE_TIME` on the `DECLARATION` table. All the data in the column will be lost.
  - You are about to drop the column `DEVICE_ID` on the `DECLARATION` table. All the data in the column will be lost.
  - You are about to drop the column `EOD_ID` on the `DECLARATION` table. All the data in the column will be lost.
  - You are about to drop the column `IS_DELETED` on the `DECLARATION` table. All the data in the column will be lost.
  - You are about to drop the column `OPENED_BY` on the `DECLARATION` table. All the data in the column will be lost.
  - You are about to drop the column `OPENING_DATE_TIME` on the `DECLARATION` table. All the data in the column will be lost.
  - You are about to drop the column `OUTLET_ID` on the `DECLARATION` table. All the data in the column will be lost.
  - You are about to drop the column `VERIFIED_BY` on the `DECLARATION` table. All the data in the column will be lost.
  - You are about to drop the `EOD` table. If the table is not empty, all the data it contains will be lost.
  - Added the required column `DECLARATION_AMOUNT` to the `DECLARATION` table without a default value. This is not possible if the table is not empty.
  - Added the required column `DIFFERENCE_AMOUNT` to the `DECLARATION` table without a default value. This is not possible if the table is not empty.
  - Added the required column `PAYMENT_TYPE` to the `DECLARATION` table without a default value. This is not possible if the table is not empty.
  - Added the required column `SESSION_ID` to the `DECLARATION` table without a default value. This is not possible if the table is not empty.
  - Added the required column `TOTAL_PAYMENT_AMOUNT` to the `DECLARATION` table without a default value. This is not possible if the table is not empty.

*/
-- AlterTable
ALTER TABLE `DECLARATION` DROP COLUMN `BUSINESS_DATE`,
    DROP COLUMN `CLOSED_BY`,
    DROP COLUMN `CLOSING_DATE_TIME`,
    DROP COLUMN `DEVICE_ID`,
    DROP COLUMN `EOD_ID`,
    DROP COLUMN `IS_DELETED`,
    DROP COLUMN `OPENED_BY`,
    DROP COLUMN `OPENING_DATE_TIME`,
    DROP COLUMN `OUTLET_ID`,
    DROP COLUMN `VERIFIED_BY`,
    ADD COLUMN `CREATED_DATETIME` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `DECLARATION_AMOUNT` DECIMAL(65, 30) NOT NULL,
    ADD COLUMN `DIFFERENCE_AMOUNT` DECIMAL(65, 30) NOT NULL,
    ADD COLUMN `PAYMENT_TYPE` VARCHAR(191) NOT NULL,
    ADD COLUMN `SESSION_ID` INTEGER NOT NULL,
    ADD COLUMN `TOTAL_PAYMENT_AMOUNT` DECIMAL(65, 30) NOT NULL;

-- DropTable
DROP TABLE `EOD`;

-- CreateTable
CREATE TABLE `SESSION` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `OUTLET_ID` INTEGER NOT NULL,
    `BUSINESS_DATE` DATETIME(3) NOT NULL,
    `OPENING_DATE_TIME` DATETIME(3) NULL,
    `CLOSING_DATE_TIME` DATETIME(3) NULL,
    `OPENING_AMOUNT` DECIMAL(65, 30) NOT NULL,
    `TOTAL_SALES_COUNT` INTEGER NOT NULL,
    `OPEN_BY_USER_ID` INTEGER NOT NULL,
    `CLOSE_BY_USER_ID` INTEGER NOT NULL,
    `CREATED_DATETIME` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MENU_PROFILE_OUTLET` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `MENU_PROFILE_ID` INTEGER NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MENU_PROFILE` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CREATED_DATETIME` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `DATE_START` VARCHAR(191) NOT NULL,
    `DATE_END` VARCHAR(191) NOT NULL,
    `TIME_START` VARCHAR(191) NOT NULL,
    `TIME_END` VARCHAR(191) NOT NULL,
    `IS_MONDAY` BOOLEAN NOT NULL,
    `IS_TUESDAY` BOOLEAN NOT NULL,
    `IS_WEDNESDAY` BOOLEAN NOT NULL,
    `IS_THURSDAY` BOOLEAN NOT NULL,
    `IS_FRIDAY` BOOLEAN NOT NULL,
    `IS_SATURDAY` BOOLEAN NOT NULL,
    `IS_SUNDAY` BOOLEAN NOT NULL,
    `SEQUENCE` INTEGER NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MENU_CATEGORY` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CREATED_DATETIME` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `NAME` VARCHAR(191) NOT NULL,
    `MENU_PROFILE_ID` INTEGER NOT NULL,
    `IMAGE_URL` VARCHAR(191) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MENU_ITEM` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CREATED_DATETIME` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `NAME` VARCHAR(191) NOT NULL,
    `ITEM_ID` INTEGER NOT NULL,
    `ITEM_CODE` VARCHAR(191) NOT NULL,
    `IMAGE_URL` VARCHAR(191) NULL,
    `PRICE` DECIMAL(65, 30) NOT NULL,
    `SEQUENCE` INTEGER NOT NULL,
    `MENU_CATEGORY_ID` INTEGER NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MENU_ITEM_MODIFIER_GROUP` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `MIN_SELECTION` INTEGER NOT NULL,
    `MAX_SELECTION` INTEGER NOT NULL,
    `SEQUENCE` INTEGER NOT NULL,
    `MENU_ITEM_ID` INTEGER NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MENU_ITEM_MODIFIER` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `ITEM_ID` INTEGER NOT NULL,
    `ITEM_CODE` VARCHAR(191) NOT NULL,
    `IMAGE_URL` VARCHAR(191) NULL,
    `PRICE` DECIMAL(65, 30) NOT NULL,
    `DEFAULT_SELECTION_QTY` INTEGER NOT NULL,
    `SEQUENCE` INTEGER NOT NULL,
    `MENU_ITEM_MODIFIER_GROUP_ID` INTEGER NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `SALES_ITEM` ADD CONSTRAINT `SALES_ITEM_SALES_ID_fkey` FOREIGN KEY (`SALES_ID`) REFERENCES `SALES`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SALES_QUOTATION_ITEM` ADD CONSTRAINT `SALES_QUOTATION_ITEM_SALES_QUOTATION_ID_fkey` FOREIGN KEY (`SALES_QUOTATION_ID`) REFERENCES `SALES_QUOTATION`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DELIVERY_ORDER_ITEM` ADD CONSTRAINT `DELIVERY_ORDER_ITEM_DELIVERY_ORDER_ID_fkey` FOREIGN KEY (`DELIVERY_ORDER_ID`) REFERENCES `DELIVERY_ORDER`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PURCHASE_ORDER_ITEM` ADD CONSTRAINT `PURCHASE_ORDER_ITEM_PURCHASE_ORDER_ID_fkey` FOREIGN KEY (`PURCHASE_ORDER_ID`) REFERENCES `PURCHASE_ORDER`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PAYMENT` ADD CONSTRAINT `PAYMENT_SALES_ID_fkey` FOREIGN KEY (`SALES_ID`) REFERENCES `SALES`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `REGISTER_LOG` ADD CONSTRAINT `REGISTER_LOG_SALES_ID_fkey` FOREIGN KEY (`SALES_ID`) REFERENCES `SALES`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CARD_INFO` ADD CONSTRAINT `CARD_INFO_PAYMENT_ID_fkey` FOREIGN KEY (`PAYMENT_ID`) REFERENCES `PAYMENT`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DECLARATION` ADD CONSTRAINT `DECLARATION_SESSION_ID_fkey` FOREIGN KEY (`SESSION_ID`) REFERENCES `SESSION`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `STOCK` ADD CONSTRAINT `STOCK_ITEM_CODE_fkey` FOREIGN KEY (`ITEM_CODE`) REFERENCES `ITEM`(`ITEM_CODE`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `STOCK_CHECK` ADD CONSTRAINT `STOCK_CHECK_ITEM_CODE_fkey` FOREIGN KEY (`ITEM_CODE`) REFERENCES `ITEM`(`ITEM_CODE`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MENU_CATEGORY` ADD CONSTRAINT `MENU_CATEGORY_MENU_PROFILE_ID_fkey` FOREIGN KEY (`MENU_PROFILE_ID`) REFERENCES `MENU_PROFILE`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MENU_ITEM` ADD CONSTRAINT `MENU_ITEM_MENU_CATEGORY_ID_fkey` FOREIGN KEY (`MENU_CATEGORY_ID`) REFERENCES `MENU_CATEGORY`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MENU_ITEM_MODIFIER_GROUP` ADD CONSTRAINT `MENU_ITEM_MODIFIER_GROUP_MENU_ITEM_ID_fkey` FOREIGN KEY (`MENU_ITEM_ID`) REFERENCES `MENU_ITEM`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MENU_ITEM_MODIFIER` ADD CONSTRAINT `MENU_ITEM_MODIFIER_MENU_ITEM_MODIFIER_GROUP_ID_fkey` FOREIGN KEY (`MENU_ITEM_MODIFIER_GROUP_ID`) REFERENCES `MENU_ITEM_MODIFIER_GROUP`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
