-- CreateTable
CREATE TABLE `purchase_return` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `RETURN_NUMBER` VARCHAR(191) NOT NULL,
    `INVOICE_ID` INTEGER NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `SUPPLIER_ID` INTEGER NOT NULL,
    `RETURN_DATE` DATETIME(3) NOT NULL,
    `STATUS` VARCHAR(191) NOT NULL DEFAULT 'COMPLETED',
    `TOTAL_RETURN_AMOUNT` DECIMAL(15, 4) NULL,
    `REMARK` VARCHAR(191) NULL DEFAULT '',
    `PERFORMED_BY` VARCHAR(191) NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    UNIQUE INDEX `purchase_return_RETURN_NUMBER_key`(`RETURN_NUMBER`),
    INDEX `purchase_return_INVOICE_ID_idx`(`INVOICE_ID`),
    INDEX `purchase_return_SUPPLIER_ID_idx`(`SUPPLIER_ID`),
    INDEX `purchase_return_OUTLET_ID_idx`(`OUTLET_ID`),
    INDEX `purchase_return_RETURN_DATE_idx`(`RETURN_DATE`),
    INDEX `purchase_return_STATUS_idx`(`STATUS`),
    INDEX `purchase_return_CREATED_AT_UPDATED_AT_DELETED_AT_idx`(`CREATED_AT`, `UPDATED_AT`, `DELETED_AT`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `purchase_return_item` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PURCHASE_RETURN_ID` INTEGER NOT NULL,
    `ITEM_ID` INTEGER NOT NULL,
    `ITEM_VARIANT_ID` INTEGER NULL,
    `VARIANT_SKU` VARCHAR(191) NULL,
    `VARIANT_NAME` VARCHAR(191) NULL,
    `QUANTITY` DECIMAL(15, 4) NOT NULL,
    `UNIT_PRICE` DECIMAL(15, 4) NOT NULL,
    `RETURN_REASON` VARCHAR(191) NOT NULL,
    `REMARK` VARCHAR(191) NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `purchase_return_item_PURCHASE_RETURN_ID_idx`(`PURCHASE_RETURN_ID`),
    INDEX `purchase_return_item_ITEM_ID_idx`(`ITEM_ID`),
    INDEX `purchase_return_item_ITEM_VARIANT_ID_idx`(`ITEM_VARIANT_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `purchase_return` ADD CONSTRAINT `purchase_return_INVOICE_ID_fkey` FOREIGN KEY (`INVOICE_ID`) REFERENCES `invoice`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `purchase_return` ADD CONSTRAINT `purchase_return_SUPPLIER_ID_fkey` FOREIGN KEY (`SUPPLIER_ID`) REFERENCES `supplier`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `purchase_return` ADD CONSTRAINT `purchase_return_OUTLET_ID_fkey` FOREIGN KEY (`OUTLET_ID`) REFERENCES `outlet`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `purchase_return_item` ADD CONSTRAINT `purchase_return_item_PURCHASE_RETURN_ID_fkey` FOREIGN KEY (`PURCHASE_RETURN_ID`) REFERENCES `purchase_return`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `purchase_return_item` ADD CONSTRAINT `purchase_return_item_ITEM_ID_fkey` FOREIGN KEY (`ITEM_ID`) REFERENCES `item`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `purchase_return_item` ADD CONSTRAINT `purchase_return_item_ITEM_VARIANT_ID_fkey` FOREIGN KEY (`ITEM_VARIANT_ID`) REFERENCES `item_variant`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;
