-- CreateTable
CREATE TABLE `ROLE` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `CATEGORY` VARCHAR(191) NULL,
    `DESCRIPTION` VARCHAR(191) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    UNIQUE INDEX `ROLE_NAME_key`(`NAME`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ROLE_PERMISSION` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ROLE_ID` INTEGER NOT NULL,
    `PERMISSION_ID` INTEGER NOT NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    UNIQUE INDEX `ROLE_PERMISSION_ROLE_ID_PERMISSION_ID_key`(`ROLE_ID`, `PERMISSION_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `USER` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USERNAME` VARCHAR(191) NOT NULL,
    `PASSWORD` VARCHAR(191) NOT NULL,
    `OVERRIDE_PIN` VARCHAR(191) NULL,
    `LAST_NAME` VARCHAR(191) NULL,
    `FIRST_NAME` VARCHAR(191) NULL,
    `MOBILE` VARCHAR(191) NULL,
    `EMAIL` VARCHAR(191) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    UNIQUE INDEX `USER_USERNAME_key`(`USERNAME`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OVERRIDE_LOG` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USER_ID` INTEGER NOT NULL,
    `APPROVER_ID` INTEGER NOT NULL,
    `ACTION` VARCHAR(191) NOT NULL,
    `REASON` VARCHAR(191) NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SETTING` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TENANT_ID` INTEGER NULL,
    `USER_ID` INTEGER NULL,
    `OUTLET_ID` INTEGER NULL,
    `KEY` VARCHAR(191) NOT NULL,
    `VALUE` VARCHAR(191) NOT NULL,
    `TYPE` ENUM('INT', 'STRING', 'BOOLEAN', 'JSON') NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `SETTING_KEY_idx`(`KEY`),
    UNIQUE INDEX `SETTING_TENANT_ID_USER_ID_OUTLET_ID_KEY_key`(`TENANT_ID`, `USER_ID`, `OUTLET_ID`, `KEY`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `REFERRAL` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USER_ID` INTEGER NOT NULL,
    `REFERRAL_ID` INTEGER NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SUPPLIER` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `COMPANY_NAME` VARCHAR(191) NOT NULL,
    `COMPANY_STREET` VARCHAR(191) NULL,
    `COMPANY_CITY` VARCHAR(191) NULL,
    `COMPANY_STATE` VARCHAR(191) NULL,
    `COMPANY_POSTAL_CODE` VARCHAR(191) NULL,
    `COMPANY_COUNTRY` VARCHAR(191) NULL,
    `COMPANY_REGISTRATION_NUMBER` VARCHAR(191) NULL,
    `PERSON_IN_CHARGE_LAST_NAME` VARCHAR(191) NULL,
    `PERSON_IN_CHARGE_FIRST_NAME` VARCHAR(191) NULL,
    `MOBILE` VARCHAR(191) NULL,
    `EMAIL` VARCHAR(191) NULL,
    `REMARK` VARCHAR(191) NULL,
    `HAS_TAX` BOOLEAN NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    UNIQUE INDEX `SUPPLIER_COMPANY_NAME_key`(`COMPANY_NAME`),
    INDEX `SUPPLIER_COMPANY_NAME_idx`(`COMPANY_NAME`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CUSTOMER` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `SALUTATION` VARCHAR(191) NOT NULL DEFAULT '',
    `LAST_NAME` VARCHAR(191) NOT NULL,
    `FIRST_NAME` VARCHAR(191) NOT NULL,
    `MOBILE` VARCHAR(191) NULL,
    `EMAIL` VARCHAR(191) NULL,
    `GENDER` VARCHAR(191) NULL,
    `BILL_STREET` VARCHAR(191) NULL,
    `BILL_CITY` VARCHAR(191) NULL,
    `BILL_STATE` VARCHAR(191) NULL,
    `BILL_POSTAL_CODE` VARCHAR(191) NULL,
    `BILL_COUNTRY` VARCHAR(191) NULL,
    `BILL_REMARK` VARCHAR(191) NULL,
    `SHIP_STREET` VARCHAR(191) NULL,
    `SHIP_CITY` VARCHAR(191) NULL,
    `SHIP_STATE` VARCHAR(191) NULL,
    `SHIP_POSTAL_CODE` VARCHAR(191) NULL,
    `SHIP_COUNTRY` VARCHAR(191) NULL,
    `SHIP_REMARK` VARCHAR(191) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `COMPANY` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `COMPANY_NAME` VARCHAR(191) NOT NULL DEFAULT '',
    `STREET` VARCHAR(191) NOT NULL DEFAULT '',
    `CITY` VARCHAR(191) NOT NULL DEFAULT '',
    `STATE` VARCHAR(191) NOT NULL DEFAULT '',
    `POSTAL_CODE` VARCHAR(191) NOT NULL DEFAULT '',
    `COUNTRY` VARCHAR(191) NOT NULL DEFAULT '',
    `REGISTRATION_NUMBER` VARCHAR(191) NOT NULL,
    `WEBSITE` VARCHAR(191) NOT NULL DEFAULT '',
    `REFERRAL_ID` VARCHAR(191) NOT NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    UNIQUE INDEX `COMPANY_REGISTRATION_NUMBER_key`(`REGISTRATION_NUMBER`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OUTLET` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TENANT_OUTLET_ID` INTEGER NOT NULL,
    `OUTLET_NAME` VARCHAR(191) NOT NULL,
    `STREET` VARCHAR(191) NOT NULL DEFAULT '',
    `CITY` VARCHAR(191) NOT NULL DEFAULT '',
    `STATE` VARCHAR(191) NOT NULL DEFAULT '',
    `POSTAL_CODE` VARCHAR(191) NOT NULL DEFAULT '',
    `COUNTRY` VARCHAR(191) NOT NULL DEFAULT '',
    `OUTLET_TEL` VARCHAR(191) NOT NULL DEFAULT '',
    `OUTLET_EMAIL` VARCHAR(191) NOT NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ITEM` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ITEM_NAME` VARCHAR(191) NOT NULL,
    `ITEM_CODE` VARCHAR(191) NOT NULL,
    `ITEM_TYPE` VARCHAR(191) NOT NULL DEFAULT '',
    `ITEM_MODEL` VARCHAR(191) NOT NULL DEFAULT '',
    `ITEM_BRAND` VARCHAR(191) NOT NULL DEFAULT '',
    `ITEM_DESCRIPTION` VARCHAR(191) NULL DEFAULT '',
    `CATEGORY_ID` INTEGER NOT NULL,
    `COST` DECIMAL(15, 4) NOT NULL,
    `PRICE` DECIMAL(15, 4) NOT NULL,
    `CURRENCY` VARCHAR(191) NOT NULL DEFAULT 'IDR',
    `IS_OPEN_PRICE` BOOLEAN NULL DEFAULT false,
    `UNIT_OF_MEASURE` VARCHAR(191) NOT NULL DEFAULT '',
    `HEIGHT` DOUBLE NULL DEFAULT 0,
    `WIDTH` DOUBLE NULL DEFAULT 0,
    `LENGTH` DOUBLE NULL DEFAULT 0,
    `WEIGHT` DOUBLE NULL DEFAULT 0,
    `ALTERNATE_LOOKUP` VARCHAR(191) NULL DEFAULT '',
    `IMAGE` VARCHAR(191) NULL DEFAULT '',
    `HAS_TAX` BOOLEAN NULL,
    `TAX_RATE` DOUBLE NULL,
    `SUPPLIER_ID` INTEGER NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `ITEM_CREATED_AT_idx`(`CREATED_AT`),
    INDEX `ITEM_DELETED_AT_idx`(`DELETED_AT`),
    INDEX `ITEM_CATEGORY_ID_idx`(`CATEGORY_ID`),
    INDEX `ITEM_UPDATED_AT_idx`(`UPDATED_AT`),
    INDEX `ITEM_SUPPLIER_ID_idx`(`SUPPLIER_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ITEM_CATEGORY` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `DESCRIPTION` VARCHAR(191) NULL DEFAULT '',
    `PARENT_ID` INTEGER NULL,
    `IMAGE` VARCHAR(191) NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    UNIQUE INDEX `ITEM_CATEGORY_NAME_key`(`NAME`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SALES` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `OUTLET_ID` INTEGER NOT NULL,
    `BUSINESS_DATE` DATETIME(3) NOT NULL,
    `SALES_TYPE` VARCHAR(191) NOT NULL,
    `CUSTOMER_NAME` VARCHAR(191) NULL DEFAULT '',
    `CUSTOMER_ID` INTEGER NULL,
    `PHONE_NUMBER` VARCHAR(191) NULL DEFAULT '',
    `BILL_STREET` VARCHAR(191) NOT NULL DEFAULT '',
    `BILL_CITY` VARCHAR(191) NOT NULL DEFAULT '',
    `BILL_STATE` VARCHAR(191) NOT NULL DEFAULT '',
    `BILL_POSTAL_CODE` VARCHAR(191) NOT NULL DEFAULT '',
    `BILL_COUNTRY` VARCHAR(191) NOT NULL DEFAULT '',
    `SHIP_STREET` VARCHAR(191) NOT NULL DEFAULT '',
    `SHIP_CITY` VARCHAR(191) NOT NULL DEFAULT '',
    `SHIP_STATE` VARCHAR(191) NOT NULL DEFAULT '',
    `SHIP_POSTAL_CODE` VARCHAR(191) NOT NULL DEFAULT '',
    `SHIP_COUNTRY` VARCHAR(191) NOT NULL DEFAULT '',
    `TOTAL_ITEM_DISCOUNT_AMOUNT` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `DISCOUNT_PERCENTAGE` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `DISCOUNT_AMOUNT` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `PROFIT_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `SERVICE_CHARGE_AMOUNT` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `TAX_AMOUNT` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `ROUNDING_AMOUNT` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `SUBTOTAL_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `TOTAL_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `PAID_AMOUNT` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `CHANGE_AMOUNT` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `STATUS` VARCHAR(191) NOT NULL,
    `REMARK` VARCHAR(191) NOT NULL DEFAULT '',
    `COMPLETED_SESSION_ID` INTEGER NULL,
    `SESSION_ID` INTEGER NOT NULL,
    `EOD_ID` INTEGER NOT NULL,
    `SALES_QUOTATION_ID` INTEGER NOT NULL DEFAULT 0,
    `PERFORMED_BY` VARCHAR(191) NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,
    `TABLE_ID` INTEGER NULL,
    `ORDER_STATUS` VARCHAR(191) NULL,

    INDEX `SALES_BUSINESS_DATE_idx`(`BUSINESS_DATE`),
    INDEX `SALES_OUTLET_ID_idx`(`OUTLET_ID`),
    INDEX `SALES_SESSION_ID_COMPLETED_SESSION_ID_idx`(`SESSION_ID`, `COMPLETED_SESSION_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SALES_ITEM` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `SALES_ID` INTEGER NOT NULL,
    `ITEM_ID` INTEGER NOT NULL,
    `ITEM_NAME` VARCHAR(191) NOT NULL,
    `ITEM_CODE` VARCHAR(191) NOT NULL,
    `ITEM_BRAND` VARCHAR(191) NOT NULL,
    `ITEM_MODEL` VARCHAR(191) NOT NULL DEFAULT '',
    `QUANTITY` DECIMAL(15, 4) NOT NULL,
    `COST` DECIMAL(15, 4) NOT NULL,
    `PRICE` DECIMAL(15, 4) NOT NULL,
    `PRICE_BEFORE_TAX` DECIMAL(15, 4) NOT NULL,
    `PROFIT` DECIMAL(15, 4) NOT NULL,
    `DISCOUNT_PERCENTAGE` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `DISCOUNT_AMOUNT` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `SERVICE_CHARGE_AMOUNT` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `TAX_AMOUNT` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `SUBTOTAL_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `REMARK` VARCHAR(191) NOT NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,
    `SPECIAL_INSTRUCTIONS` VARCHAR(191) NULL DEFAULT '',
    `ITEM_STATUS` VARCHAR(191) NULL,
    `PRIORITY` VARCHAR(191) NULL,
    `ESTIMATED_PREP_TIME` INTEGER NULL,

    INDEX `SALES_ITEM_ITEM_STATUS_idx`(`ITEM_STATUS`),
    INDEX `SALES_ITEM_ITEM_ID_idx`(`ITEM_ID`),
    INDEX `SALES_ITEM_QUANTITY_idx`(`QUANTITY`),
    INDEX `SALES_ITEM_PROFIT_idx`(`PROFIT`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SALES_ITEM_MODIFIER` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `SALES_ITEM_ID` INTEGER NOT NULL,
    `MENU_ITEM_MODIFIER_ID` INTEGER NOT NULL,
    `ITEM_ID` INTEGER NULL,
    `MODIFIER_NAME` VARCHAR(191) NOT NULL,
    `MODIFIER_PRICE` DECIMAL(15, 4) NOT NULL,
    `QUANTITY` INTEGER NOT NULL DEFAULT 1,
    `STATUS` ENUM('ORDERED', 'PREPARING', 'SERVED', 'DELIVERED', 'CANCELLED') NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `SALES_ITEM_MODIFIER_SALES_ITEM_ID_idx`(`SALES_ITEM_ID`),
    INDEX `SALES_ITEM_MODIFIER_MENU_ITEM_MODIFIER_ID_idx`(`MENU_ITEM_MODIFIER_ID`),
    INDEX `SALES_ITEM_MODIFIER_ITEM_ID_idx`(`ITEM_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SALES_QUOTATION` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `OUTLET_ID` INTEGER NOT NULL,
    `CUSTOMER_ID` INTEGER NULL,
    `CUSTOMER_STREET` VARCHAR(191) NULL,
    `CUSTOMER_CITY` VARCHAR(191) NULL,
    `CUSTOMER_STATE` VARCHAR(191) NULL,
    `CUSTOMER_POSTAL_CODE` VARCHAR(191) NULL,
    `CUSTOMER_COUNTRY` VARCHAR(191) NULL,
    `DISCOUNT_PERCENTAGE` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `DISCOUNT_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `SERVICE_CHARGE_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `TAX_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `ROUNDING_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `SUBTOTAL_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `TOTAL_AMOUNT` DECIMAL(65, 30) NOT NULL,
    `STATUS` VARCHAR(191) NOT NULL,
    `REMARK` VARCHAR(191) NULL,
    `PERFORMED_BY` VARCHAR(191) NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SALES_QUOTATION_ITEM` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `SALES_QUOTATION_ID` INTEGER NOT NULL,
    `ITEM_ID` INTEGER NOT NULL,
    `QUANTITY` DECIMAL(15, 4) NOT NULL,
    `REMARK` VARCHAR(191) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `INVOICE` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `INVOICE_NUMBER` VARCHAR(191) NOT NULL,
    `TAX_INVOICE_NUMBER` VARCHAR(191) NOT NULL,
    `PURCHASE_ORDER_ID` INTEGER NULL,
    `SUPPLIER_ID` INTEGER NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `SUBTOTAL_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `TAX_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `SESSION_ID` INTEGER NULL,
    `DISCOUNT_TYPE` VARCHAR(191) NULL DEFAULT '',
    `DISCOUNT_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `TOTAL_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `CURRENCY` VARCHAR(191) NOT NULL,
    `STATUS` VARCHAR(191) NOT NULL,
    `INVOICE_DATE` DATETIME(3) NULL,
    `PAYMENT_DATE` DATETIME(3) NULL,
    `DUE_DATE` DATETIME(3) NULL,
    `REMARK` VARCHAR(191) NULL DEFAULT '',
    `PERFORMED_BY` VARCHAR(191) NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    UNIQUE INDEX `INVOICE_INVOICE_NUMBER_key`(`INVOICE_NUMBER`),
    INDEX `INVOICE_PURCHASE_ORDER_ID_idx`(`PURCHASE_ORDER_ID`),
    INDEX `INVOICE_SUPPLIER_ID_idx`(`SUPPLIER_ID`),
    INDEX `INVOICE_OUTLET_ID_idx`(`OUTLET_ID`),
    INDEX `INVOICE_CREATED_AT_UPDATED_AT_DELETED_AT_idx`(`CREATED_AT`, `UPDATED_AT`, `DELETED_AT`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `INVOICE_ITEM` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `INVOICE_ID` INTEGER NOT NULL,
    `ITEM_ID` INTEGER NOT NULL,
    `QUANTITY` DECIMAL(15, 4) NOT NULL,
    `UNIT_PRICE` DECIMAL(15, 4) NOT NULL,
    `DISCOUNT_TYPE` VARCHAR(191) NULL DEFAULT '',
    `DISCOUNT_AMOUNT` DECIMAL(65, 30) NULL DEFAULT 0,
    `TAX_AMOUNT` DECIMAL(15, 4) NULL,
    `SUBTOTAL` DECIMAL(15, 4) NOT NULL,
    `REMARK` VARCHAR(191) NULL DEFAULT '',
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `INVOICE_ITEM_INVOICE_ID_idx`(`INVOICE_ID`),
    INDEX `INVOICE_ITEM_ITEM_ID_idx`(`ITEM_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DELIVERY_ORDER` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TRACKING_NUMBER` VARCHAR(191) NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `CUSTOMER_ID` INTEGER NULL,
    `PURCHASE_ORDER_ID` INTEGER NULL,
    `SUPPLIER_ID` INTEGER NULL,
    `INVOICE_ID` INTEGER NULL,
    `SESSION_ID` INTEGER NULL,
    `DELIVERY_DATE` DATETIME(3) NULL,
    `DELIVERY_STREET` VARCHAR(191) NULL,
    `DELIVERY_CITY` VARCHAR(191) NULL,
    `DELIVERY_STATE` VARCHAR(191) NULL,
    `DELIVERY_POSTAL_CODE` VARCHAR(191) NULL,
    `DELIVERY_COUNTRY` VARCHAR(191) NULL,
    `STATUS` VARCHAR(191) NOT NULL,
    `REMARK` VARCHAR(191) NULL,
    `PERFORMED_BY` VARCHAR(191) NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `DELIVERY_ORDER_OUTLET_ID_idx`(`OUTLET_ID`),
    INDEX `DELIVERY_ORDER_CUSTOMER_ID_idx`(`CUSTOMER_ID`),
    INDEX `DELIVERY_ORDER_PURCHASE_ORDER_ID_idx`(`PURCHASE_ORDER_ID`),
    INDEX `DELIVERY_ORDER_INVOICE_ID_SUPPLIER_ID_idx`(`INVOICE_ID`, `SUPPLIER_ID`),
    INDEX `DELIVERY_ORDER_CREATED_AT_UPDATED_AT_DELETED_AT_idx`(`CREATED_AT`, `UPDATED_AT`, `DELETED_AT`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DELIVERY_ORDER_ITEM` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DELIVERY_ORDER_ID` INTEGER NOT NULL,
    `ITEM_ID` INTEGER NOT NULL,
    `ORDERED_QUANTITY` DOUBLE NOT NULL,
    `RECEIVED_QUANTITY` DOUBLE NOT NULL,
    `UNIT_PRICE` DECIMAL(15, 4) NULL DEFAULT 0,
    `DELIVERY_FEE` DECIMAL(15, 4) NULL DEFAULT 0,
    `REMARK` VARCHAR(191) NULL DEFAULT '',
    `VERSION` INTEGER NULL DEFAULT 1,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,

    INDEX `DELIVERY_ORDER_ITEM_DELIVERY_ORDER_ID_idx`(`DELIVERY_ORDER_ID`),
    INDEX `DELIVERY_ORDER_ITEM_ITEM_ID_idx`(`ITEM_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PURCHASE_ORDER` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PURCHASE_ORDER_NUMBER` VARCHAR(191) NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `SUPPLIER_ID` INTEGER NOT NULL,
    `PURCHASE_ORDER_DATE` DATETIME(3) NULL,
    `SESSION_ID` INTEGER NULL,
    `DISCOUNT_TYPE` VARCHAR(191) NULL DEFAULT '',
    `DISCOUNT_AMOUNT` DECIMAL(15, 4) NULL,
    `SERVICE_CHARGE_AMOUNT` DECIMAL(15, 4) NULL,
    `TAX_AMOUNT` DECIMAL(15, 4) NULL,
    `ROUNDING_AMOUNT` DECIMAL(15, 4) NULL,
    `SUBTOTAL_AMOUNT` DECIMAL(15, 4) NULL,
    `TOTAL_AMOUNT` DECIMAL(15, 4) NULL,
    `STATUS` VARCHAR(191) NOT NULL,
    `REMARK` VARCHAR(191) NULL,
    `CURRENCY` VARCHAR(191) NOT NULL DEFAULT 'IDR',
    `PERFORMED_BY` VARCHAR(191) NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    UNIQUE INDEX `PURCHASE_ORDER_PURCHASE_ORDER_NUMBER_key`(`PURCHASE_ORDER_NUMBER`),
    INDEX `PURCHASE_ORDER_SUPPLIER_ID_idx`(`SUPPLIER_ID`),
    INDEX `PURCHASE_ORDER_OUTLET_ID_idx`(`OUTLET_ID`),
    INDEX `PURCHASE_ORDER_CREATED_AT_UPDATED_AT_DELETED_AT_idx`(`CREATED_AT`, `UPDATED_AT`, `DELETED_AT`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PURCHASE_ORDER_ITEM` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PURCHASE_ORDER_ID` INTEGER NOT NULL,
    `ITEM_ID` INTEGER NOT NULL,
    `QUANTITY` DECIMAL(15, 4) NOT NULL,
    `TAX_AMOUNT` DECIMAL(15, 4) NULL,
    `DISCOUNT_TYPE` VARCHAR(191) NULL DEFAULT '',
    `DISCOUNT_AMOUNT` DECIMAL(65, 30) NULL DEFAULT 0,
    `UNIT_PRICE` DECIMAL(15, 4) NOT NULL,
    `SUBTOTAL` DECIMAL(15, 4) NOT NULL,
    `REMARK` VARCHAR(191) NULL DEFAULT '',
    `VERSION` INTEGER NULL DEFAULT 1,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,

    INDEX `PURCHASE_ORDER_ITEM_PURCHASE_ORDER_ID_idx`(`PURCHASE_ORDER_ID`),
    INDEX `PURCHASE_ORDER_ITEM_ITEM_ID_idx`(`ITEM_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PAYMENT` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PAYMENT` VARCHAR(191) NOT NULL,
    `TENDERED_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `PAID_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `CURRENCY_SYMBOL` VARCHAR(191) NOT NULL DEFAULT '',
    `SALES_ID` INTEGER NOT NULL,
    `REFERENCE` VARCHAR(191) NOT NULL DEFAULT '',
    `REMARK` VARCHAR(191) NOT NULL DEFAULT '',
    `BUSINESS_DATE` DATETIME(3) NOT NULL,
    `STATUS` VARCHAR(191) NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `SESSION_ID` INTEGER NOT NULL,
    `EOD_ID` INTEGER NOT NULL,
    `PERFORMED_BY` VARCHAR(191) NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `PAYMENT_PAYMENT_idx`(`PAYMENT`),
    INDEX `PAYMENT_BUSINESS_DATE_idx`(`BUSINESS_DATE`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `REGISTER_LOG` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TYPE` VARCHAR(191) NOT NULL,
    `MODIFIED_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `CURRENCY_SYMBOL` VARCHAR(191) NOT NULL DEFAULT '',
    `SALES_ID` INTEGER NOT NULL,
    `REMARK` VARCHAR(191) NOT NULL DEFAULT '',
    `STATUS` VARCHAR(191) NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `SESSION_ID` INTEGER NOT NULL,
    `EOD_ID` INTEGER NOT NULL,
    `PERFORMED_BY` VARCHAR(191) NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CARD_INFO` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PAYMENT_ID` INTEGER NOT NULL,
    `CARD_NUMBER` VARCHAR(191) NULL,
    `CARD_EXPIRY` VARCHAR(191) NULL,
    `TRACE_NUMBER` VARCHAR(191) NULL,
    `TYPE_2` VARCHAR(191) NULL,
    `TYPE_3` VARCHAR(191) NULL,
    `CARD_RATE` DOUBLE NULL,
    `APP_CODE` VARCHAR(191) NULL,
    `CARD_TYPE` VARCHAR(191) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SESSION` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `OUTLET_ID` INTEGER NOT NULL,
    `BUSINESS_DATE` DATETIME(3) NOT NULL,
    `OPENING_DATE_TIME` DATETIME(3) NULL,
    `CLOSING_DATE_TIME` DATETIME(3) NULL,
    `OPENING_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `TOTAL_SALES_COUNT` INTEGER NOT NULL,
    `OPEN_BY_USER_ID` INTEGER NOT NULL,
    `CLOSE_BY_USER_ID` INTEGER NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DECLARATION` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PAYMENT_TYPE` VARCHAR(191) NOT NULL,
    `TOTAL_PAYMENT_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `DECLARATION_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `DIFFERENCE_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,
    `SESSION_ID` INTEGER NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `STOCK_BALANCE` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ITEM_ID` INTEGER NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `AVAILABLE_QUANTITY` DECIMAL(15, 4) NOT NULL,
    `ON_HAND_QUANTITY` DECIMAL(15, 4) NOT NULL,
    `REORDER_THRESHOLD` DECIMAL(15, 4) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `LAST_RESTOCK_DATE` DATETIME(3) NULL,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    UNIQUE INDEX `STOCK_BALANCE_ITEM_ID_OUTLET_ID_REORDER_THRESHOLD_IS_DELETED_key`(`ITEM_ID`, `OUTLET_ID`, `REORDER_THRESHOLD`, `IS_DELETED`, `AVAILABLE_QUANTITY`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `STOCK_RECEIPT` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ITEM_ID` INTEGER NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `QUANTITY` DECIMAL(15, 4) NOT NULL,
    `COST` DECIMAL(15, 4) NOT NULL,
    `RECEIPT_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `STOCK_RECEIPT_ARCHIVE` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ITEM_ID` INTEGER NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `QUANTITY` DECIMAL(15, 4) NOT NULL,
    `COST` DECIMAL(15, 4) NOT NULL,
    `RECEIPT_DATE` DATETIME(3) NOT NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `STOCK_RECEIPT_ARCHIVE_ITEM_ID_RECEIPT_DATE_idx`(`ITEM_ID`, `RECEIPT_DATE`),
    INDEX `STOCK_RECEIPT_ARCHIVE_OUTLET_ID_idx`(`OUTLET_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `STOCK_MOVEMENT` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ITEM_ID` INTEGER NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `PREVIOUS_AVAILABLE_QUANTITY` DECIMAL(15, 4) NOT NULL,
    `PREVIOUS_ON_HAND_QUANTITY` DECIMAL(15, 4) NOT NULL,
    `AVAILABLE_QUANTITY_DELTA` DECIMAL(15, 4) NOT NULL,
    `ON_HAND_QUANTITY_DELTA` DECIMAL(15, 4) NOT NULL,
    `MOVEMENT_TYPE` VARCHAR(191) NOT NULL,
    `DOCUMENT_ID` INTEGER NOT NULL,
    `REASON` VARCHAR(191) NOT NULL,
    `REMARK` VARCHAR(191) NOT NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,
    `PERFORMED_BY` VARCHAR(191) NULL DEFAULT '',

    INDEX `STOCK_MOVEMENT_ITEM_ID_CREATED_AT_idx`(`ITEM_ID`, `CREATED_AT`),
    INDEX `STOCK_MOVEMENT_OUTLET_ID_idx`(`OUTLET_ID`),
    INDEX `STOCK_MOVEMENT_MOVEMENT_TYPE_idx`(`MOVEMENT_TYPE`),
    INDEX `STOCK_MOVEMENT_IS_DELETED_idx`(`IS_DELETED`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `STOCK_MOVEMENT_ARCHIVE` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ITEM_ID` INTEGER NOT NULL,
    `ITEM_CODE` VARCHAR(191) NOT NULL,
    `ITEM_NAME` VARCHAR(191) NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `OUTLET_NAME` VARCHAR(191) NOT NULL,
    `PREVIOUS_AVAILABLE_QUANTITY` DECIMAL(15, 4) NOT NULL,
    `PREVIOUS_ON_HAND_QUANTITY` DECIMAL(15, 4) NOT NULL,
    `AVAILABLE_QUANTITY_DELTA` DECIMAL(15, 4) NOT NULL,
    `ON_HAND_QUANTITY_DELTA` DECIMAL(15, 4) NOT NULL,
    `MOVEMENT_TYPE` VARCHAR(191) NOT NULL,
    `DOCUMENT_ID` INTEGER NOT NULL,
    `DOCUMENT_TYPE` VARCHAR(191) NOT NULL,
    `REASON` VARCHAR(191) NOT NULL,
    `REMARK` VARCHAR(191) NOT NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `STOCK_MOVEMENT_ARCHIVE_ITEM_ID_CREATED_AT_idx`(`ITEM_ID`, `CREATED_AT`),
    INDEX `STOCK_MOVEMENT_ARCHIVE_OUTLET_ID_idx`(`OUTLET_ID`),
    INDEX `STOCK_MOVEMENT_ARCHIVE_MOVEMENT_TYPE_idx`(`MOVEMENT_TYPE`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `STOCK_SNAPSHOT` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ITEM_ID` INTEGER NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `AVAILABLE_QUANTITY` DECIMAL(15, 4) NOT NULL,
    `ON_HAND_QUANTITY` DECIMAL(15, 4) NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `STOCK_SNAPSHOT_ITEM_ID_CREATED_AT_idx`(`ITEM_ID`, `CREATED_AT`),
    INDEX `STOCK_SNAPSHOT_OUTLET_ID_idx`(`OUTLET_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MENU_PROFILE_OUTLET` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `OUTLET_ID` INTEGER NOT NULL,
    `MENU_PROFILE_ID` INTEGER NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MENU_PROFILE` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `DATE_START` VARCHAR(191) NOT NULL,
    `DATE_END` VARCHAR(191) NOT NULL,
    `TIME_START` VARCHAR(191) NOT NULL,
    `TIME_END` VARCHAR(191) NOT NULL,
    `IS_MONDAY` BOOLEAN NOT NULL,
    `IS_TUESDAY` BOOLEAN NOT NULL,
    `IS_WEDNESDAY` BOOLEAN NOT NULL,
    `IS_THURSDAY` BOOLEAN NOT NULL,
    `IS_FRIDAY` BOOLEAN NOT NULL,
    `IS_SATURDAY` BOOLEAN NOT NULL,
    `IS_SUNDAY` BOOLEAN NOT NULL,
    `SEQUENCE` INTEGER NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MENU_CATEGORY` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `MENU_PROFILE_ID` INTEGER NOT NULL,
    `IMAGE_URL` TEXT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MENU_ITEM` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `ITEM_ID` INTEGER NOT NULL,
    `ITEM_CODE` VARCHAR(191) NOT NULL,
    `IMAGE_URL` TEXT NULL,
    `PRICE` DECIMAL(15, 4) NOT NULL,
    `SEQUENCE` INTEGER NOT NULL,
    `MENU_CATEGORY_ID` INTEGER NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MENU_ITEM_MODIFIER_GROUP` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `MIN_SELECTION` INTEGER NOT NULL,
    `MAX_SELECTION` INTEGER NOT NULL,
    `SEQUENCE` INTEGER NOT NULL,
    `MENU_ITEM_ID` INTEGER NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,
    `FREE_MODIFIER_LIMIT` INTEGER NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MENU_ITEM_MODIFIER` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `ITEM_ID` INTEGER NOT NULL,
    `ITEM_CODE` VARCHAR(191) NOT NULL,
    `IMAGE_URL` TEXT NULL,
    `PRICE` DECIMAL(15, 4) NOT NULL,
    `DEFAULT_SELECTION_QTY` INTEGER NOT NULL,
    `SEQUENCE` INTEGER NOT NULL,
    `MENU_ITEM_MODIFIER_GROUP_ID` INTEGER NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TABLE` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `OUTLET_ID` INTEGER NOT NULL,
    `TABLE_NUMBER` VARCHAR(191) NOT NULL,
    `CAPACITY` INTEGER NOT NULL,
    `STATUS` VARCHAR(191) NOT NULL,
    `SALES_ID` INTEGER NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `RECIPE` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `MENU_ITEM_ID` INTEGER NOT NULL,
    `ITEM_ID` INTEGER NOT NULL,
    `QUANTITY` DOUBLE NOT NULL,
    `UNIT` VARCHAR(191) NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,
    `BATCH_YIELD` DOUBLE NULL,
    `MENU_ITEM_MODIFIER_ID` INTEGER NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `STATION` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `OUTLET_ID` INTEGER NOT NULL,
    `NAME` VARCHAR(191) NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `RESERVATION` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `OUTLET_ID` INTEGER NOT NULL,
    `CUSTOMER_ID` INTEGER NULL,
    `TABLE_ID` INTEGER NULL,
    `DATE_TIME` DATETIME(3) NOT NULL,
    `PARTY_SIZE` INTEGER NOT NULL,
    `STATUS` VARCHAR(191) NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ORDER_ROUTING` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `SALES_ITEM_ID` INTEGER NOT NULL,
    `STATION_ID` INTEGER NOT NULL,
    `STATUS` VARCHAR(191) NOT NULL,
    `SENT_AT` DATETIME(3) NULL,
    `COMPLETED_AT` DATETIME(3) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `WAITLIST` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `OUTLET_ID` INTEGER NOT NULL,
    `CUSTOMER_ID` INTEGER NULL,
    `PARTY_SIZE` INTEGER NOT NULL,
    `STATUS` VARCHAR(191) NOT NULL,
    `WAIT_TIME` INTEGER NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SPLIT_BILL` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `SALES_ID` INTEGER NOT NULL,
    `AMOUNT` DECIMAL(15, 4) NOT NULL,
    `PAYMENT_ID` INTEGER NULL,
    `CUSTOMER_ID` INTEGER NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PROMOTION` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `DESCRIPTION` VARCHAR(191) NULL,
    `TYPE` ENUM('DAILY', 'HOURLY', 'GENERIC', 'CUSTOMER') NOT NULL,
    `STATUS` ENUM('ACTIVE', 'INACTIVE', 'EXPIRED', 'SCHEDULED') NOT NULL DEFAULT 'ACTIVE',
    `PRIORITY` INTEGER NOT NULL DEFAULT 1,
    `COMBINATION_RULE` ENUM('STACKABLE', 'EXCLUSIVE') NOT NULL DEFAULT 'STACKABLE',
    `DISCOUNT_TYPE` ENUM('PERCENTAGE', 'FIXED_AMOUNT', 'BUY_X_GET_Y', 'BUY_X_GET_Y_DISCOUNT') NOT NULL,
    `DISCOUNT_VALUE` DECIMAL(65, 30) NULL,
    `BUY_QUANTITY` INTEGER NULL,
    `GET_QUANTITY` INTEGER NULL,
    `GET_DISCOUNT_VALUE` DECIMAL(65, 30) NULL,
    `START_DATE` DATETIME(3) NULL,
    `END_DATE` DATETIME(3) NULL,
    `START_TIME` VARCHAR(191) NULL,
    `END_TIME` VARCHAR(191) NULL,
    `VALID_DAYS` VARCHAR(191) NULL,
    `MIN_PURCHASE_AMOUNT` DECIMAL(65, 30) NULL,
    `MIN_PURCHASE_QTY` INTEGER NULL,
    `MAX_USAGE_TOTAL` INTEGER NULL,
    `MAX_USAGE_PER_CUSTOMER` INTEGER NULL,
    `CURRENT_USAGE` INTEGER NOT NULL DEFAULT 0,
    `IS_CUSTOMER_SPECIFIC` BOOLEAN NOT NULL DEFAULT false,
    `CREATED_BY` VARCHAR(191) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PROMOTION_ITEM` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PROMOTION_ID` INTEGER NOT NULL,
    `ITEM_ID` INTEGER NULL,
    `CATEGORY_ID` INTEGER NULL,
    `ITEM_CODE` VARCHAR(191) NULL,
    `ITEM_NAME` VARCHAR(191) NULL,
    `ITEM_ROLE` VARCHAR(191) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PROMOTION_CUSTOMER` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PROMOTION_ID` INTEGER NOT NULL,
    `CUSTOMER_ID` INTEGER NOT NULL,
    `MAX_USAGE` INTEGER NULL,
    `CURRENT_USAGE` INTEGER NOT NULL DEFAULT 0,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    UNIQUE INDEX `PROMOTION_CUSTOMER_PROMOTION_ID_CUSTOMER_ID_key`(`PROMOTION_ID`, `CUSTOMER_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PROMOTION_USAGE` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PROMOTION_ID` INTEGER NOT NULL,
    `CUSTOMER_ID` INTEGER NULL,
    `SALES_ID` INTEGER NULL,
    `DISCOUNT_AMOUNT` DECIMAL(65, 30) NOT NULL,
    `USED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `REGISTERED_DEVICE` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `CLIENT_DEVICE_ID` VARCHAR(191) NOT NULL,
    `SITE_ID` INTEGER NOT NULL,
    `TENANT_ID` INTEGER NOT NULL,
    `DEVICE_NAME` VARCHAR(191) NOT NULL,
    `DEVICE_TYPE` VARCHAR(191) NULL,
    `STATUS` VARCHAR(191) NOT NULL DEFAULT 'active',
    `APP_VERSION` VARCHAR(191) NULL,
    `LAST_SEEN_AT` DATETIME(3) NULL,
    `REGISTERED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    UNIQUE INDEX `REGISTERED_DEVICE_CLIENT_DEVICE_ID_key`(`CLIENT_DEVICE_ID`),
    INDEX `REGISTERED_DEVICE_CLIENT_DEVICE_ID_idx`(`CLIENT_DEVICE_ID`),
    INDEX `REGISTERED_DEVICE_TENANT_ID_idx`(`TENANT_ID`),
    UNIQUE INDEX `REGISTERED_DEVICE_TENANT_ID_SITE_ID_key`(`TENANT_ID`, `SITE_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `_USER_ROLES` (
    `A` INTEGER NOT NULL,
    `B` INTEGER NOT NULL,

    UNIQUE INDEX `_USER_ROLES_AB_unique`(`A`, `B`),
    INDEX `_USER_ROLES_B_index`(`B`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `ROLE_PERMISSION` ADD CONSTRAINT `ROLE_PERMISSION_ROLE_ID_fkey` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `OVERRIDE_LOG` ADD CONSTRAINT `OVERRIDE_LOG_USER_ID_fkey` FOREIGN KEY (`USER_ID`) REFERENCES `USER`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SETTING` ADD CONSTRAINT `SETTING_USER_ID_fkey` FOREIGN KEY (`USER_ID`) REFERENCES `USER`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SETTING` ADD CONSTRAINT `SETTING_OUTLET_ID_fkey` FOREIGN KEY (`OUTLET_ID`) REFERENCES `OUTLET`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ITEM` ADD CONSTRAINT `ITEM_CATEGORY_ID_fkey` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `ITEM_CATEGORY`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ITEM` ADD CONSTRAINT `ITEM_SUPPLIER_ID_fkey` FOREIGN KEY (`SUPPLIER_ID`) REFERENCES `SUPPLIER`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SALES` ADD CONSTRAINT `SALES_CUSTOMER_ID_fkey` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SALES` ADD CONSTRAINT `SALES_TABLE_ID_fkey` FOREIGN KEY (`TABLE_ID`) REFERENCES `TABLE`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SALES_ITEM` ADD CONSTRAINT `SALES_ITEM_SALES_ID_fkey` FOREIGN KEY (`SALES_ID`) REFERENCES `SALES`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SALES_ITEM_MODIFIER` ADD CONSTRAINT `SALES_ITEM_MODIFIER_MENU_ITEM_MODIFIER_ID_fkey` FOREIGN KEY (`MENU_ITEM_MODIFIER_ID`) REFERENCES `MENU_ITEM_MODIFIER`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SALES_ITEM_MODIFIER` ADD CONSTRAINT `SALES_ITEM_MODIFIER_SALES_ITEM_ID_fkey` FOREIGN KEY (`SALES_ITEM_ID`) REFERENCES `SALES_ITEM`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SALES_QUOTATION_ITEM` ADD CONSTRAINT `SALES_QUOTATION_ITEM_SALES_QUOTATION_ID_fkey` FOREIGN KEY (`SALES_QUOTATION_ID`) REFERENCES `SALES_QUOTATION`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `INVOICE` ADD CONSTRAINT `INVOICE_SESSION_ID_fkey` FOREIGN KEY (`SESSION_ID`) REFERENCES `SESSION`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `INVOICE` ADD CONSTRAINT `INVOICE_PURCHASE_ORDER_ID_fkey` FOREIGN KEY (`PURCHASE_ORDER_ID`) REFERENCES `PURCHASE_ORDER`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `INVOICE` ADD CONSTRAINT `INVOICE_SUPPLIER_ID_fkey` FOREIGN KEY (`SUPPLIER_ID`) REFERENCES `SUPPLIER`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `INVOICE_ITEM` ADD CONSTRAINT `INVOICE_ITEM_INVOICE_ID_fkey` FOREIGN KEY (`INVOICE_ID`) REFERENCES `INVOICE`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `INVOICE_ITEM` ADD CONSTRAINT `INVOICE_ITEM_ITEM_ID_fkey` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DELIVERY_ORDER` ADD CONSTRAINT `DELIVERY_ORDER_SESSION_ID_fkey` FOREIGN KEY (`SESSION_ID`) REFERENCES `SESSION`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DELIVERY_ORDER` ADD CONSTRAINT `DELIVERY_ORDER_PURCHASE_ORDER_ID_fkey` FOREIGN KEY (`PURCHASE_ORDER_ID`) REFERENCES `PURCHASE_ORDER`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DELIVERY_ORDER` ADD CONSTRAINT `DELIVERY_ORDER_INVOICE_ID_fkey` FOREIGN KEY (`INVOICE_ID`) REFERENCES `INVOICE`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DELIVERY_ORDER_ITEM` ADD CONSTRAINT `DELIVERY_ORDER_ITEM_DELIVERY_ORDER_ID_fkey` FOREIGN KEY (`DELIVERY_ORDER_ID`) REFERENCES `DELIVERY_ORDER`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DELIVERY_ORDER_ITEM` ADD CONSTRAINT `DELIVERY_ORDER_ITEM_ITEM_ID_fkey` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PURCHASE_ORDER` ADD CONSTRAINT `PURCHASE_ORDER_SESSION_ID_fkey` FOREIGN KEY (`SESSION_ID`) REFERENCES `SESSION`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PURCHASE_ORDER` ADD CONSTRAINT `PURCHASE_ORDER_SUPPLIER_ID_fkey` FOREIGN KEY (`SUPPLIER_ID`) REFERENCES `SUPPLIER`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PURCHASE_ORDER_ITEM` ADD CONSTRAINT `PURCHASE_ORDER_ITEM_PURCHASE_ORDER_ID_fkey` FOREIGN KEY (`PURCHASE_ORDER_ID`) REFERENCES `PURCHASE_ORDER`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PURCHASE_ORDER_ITEM` ADD CONSTRAINT `PURCHASE_ORDER_ITEM_ITEM_ID_fkey` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PAYMENT` ADD CONSTRAINT `PAYMENT_SALES_ID_fkey` FOREIGN KEY (`SALES_ID`) REFERENCES `SALES`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `REGISTER_LOG` ADD CONSTRAINT `REGISTER_LOG_SALES_ID_fkey` FOREIGN KEY (`SALES_ID`) REFERENCES `SALES`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CARD_INFO` ADD CONSTRAINT `CARD_INFO_PAYMENT_ID_fkey` FOREIGN KEY (`PAYMENT_ID`) REFERENCES `PAYMENT`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DECLARATION` ADD CONSTRAINT `DECLARATION_SESSION_ID_fkey` FOREIGN KEY (`SESSION_ID`) REFERENCES `SESSION`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `STOCK_BALANCE` ADD CONSTRAINT `STOCK_BALANCE_ITEM_ID_fkey` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `STOCK_BALANCE` ADD CONSTRAINT `STOCK_BALANCE_OUTLET_ID_fkey` FOREIGN KEY (`OUTLET_ID`) REFERENCES `OUTLET`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `STOCK_RECEIPT` ADD CONSTRAINT `STOCK_RECEIPT_ITEM_ID_fkey` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `STOCK_RECEIPT` ADD CONSTRAINT `STOCK_RECEIPT_OUTLET_ID_fkey` FOREIGN KEY (`OUTLET_ID`) REFERENCES `OUTLET`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `STOCK_MOVEMENT` ADD CONSTRAINT `STOCK_MOVEMENT_ITEM_ID_fkey` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `STOCK_MOVEMENT` ADD CONSTRAINT `STOCK_MOVEMENT_OUTLET_ID_fkey` FOREIGN KEY (`OUTLET_ID`) REFERENCES `OUTLET`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `STOCK_SNAPSHOT` ADD CONSTRAINT `STOCK_SNAPSHOT_ITEM_ID_fkey` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `STOCK_SNAPSHOT` ADD CONSTRAINT `STOCK_SNAPSHOT_OUTLET_ID_fkey` FOREIGN KEY (`OUTLET_ID`) REFERENCES `OUTLET`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MENU_CATEGORY` ADD CONSTRAINT `MENU_CATEGORY_MENU_PROFILE_ID_fkey` FOREIGN KEY (`MENU_PROFILE_ID`) REFERENCES `MENU_PROFILE`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MENU_ITEM` ADD CONSTRAINT `MENU_ITEM_MENU_CATEGORY_ID_fkey` FOREIGN KEY (`MENU_CATEGORY_ID`) REFERENCES `MENU_CATEGORY`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MENU_ITEM_MODIFIER_GROUP` ADD CONSTRAINT `MENU_ITEM_MODIFIER_GROUP_MENU_ITEM_ID_fkey` FOREIGN KEY (`MENU_ITEM_ID`) REFERENCES `MENU_ITEM`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MENU_ITEM_MODIFIER` ADD CONSTRAINT `MENU_ITEM_MODIFIER_MENU_ITEM_MODIFIER_GROUP_ID_fkey` FOREIGN KEY (`MENU_ITEM_MODIFIER_GROUP_ID`) REFERENCES `MENU_ITEM_MODIFIER_GROUP`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TABLE` ADD CONSTRAINT `TABLE_OUTLET_ID_fkey` FOREIGN KEY (`OUTLET_ID`) REFERENCES `OUTLET`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RECIPE` ADD CONSTRAINT `RECIPE_MENU_ITEM_MODIFIER_ID_fkey` FOREIGN KEY (`MENU_ITEM_MODIFIER_ID`) REFERENCES `MENU_ITEM_MODIFIER`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RECIPE` ADD CONSTRAINT `RECIPE_MENU_ITEM_ID_fkey` FOREIGN KEY (`MENU_ITEM_ID`) REFERENCES `MENU_ITEM`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RECIPE` ADD CONSTRAINT `RECIPE_ITEM_ID_fkey` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `STATION` ADD CONSTRAINT `STATION_OUTLET_ID_fkey` FOREIGN KEY (`OUTLET_ID`) REFERENCES `OUTLET`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RESERVATION` ADD CONSTRAINT `RESERVATION_OUTLET_ID_fkey` FOREIGN KEY (`OUTLET_ID`) REFERENCES `OUTLET`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RESERVATION` ADD CONSTRAINT `RESERVATION_CUSTOMER_ID_fkey` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RESERVATION` ADD CONSTRAINT `RESERVATION_TABLE_ID_fkey` FOREIGN KEY (`TABLE_ID`) REFERENCES `TABLE`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ORDER_ROUTING` ADD CONSTRAINT `ORDER_ROUTING_SALES_ITEM_ID_fkey` FOREIGN KEY (`SALES_ITEM_ID`) REFERENCES `SALES_ITEM`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ORDER_ROUTING` ADD CONSTRAINT `ORDER_ROUTING_STATION_ID_fkey` FOREIGN KEY (`STATION_ID`) REFERENCES `STATION`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `WAITLIST` ADD CONSTRAINT `WAITLIST_OUTLET_ID_fkey` FOREIGN KEY (`OUTLET_ID`) REFERENCES `OUTLET`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `WAITLIST` ADD CONSTRAINT `WAITLIST_CUSTOMER_ID_fkey` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SPLIT_BILL` ADD CONSTRAINT `SPLIT_BILL_PAYMENT_ID_fkey` FOREIGN KEY (`PAYMENT_ID`) REFERENCES `PAYMENT`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SPLIT_BILL` ADD CONSTRAINT `SPLIT_BILL_CUSTOMER_ID_fkey` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PROMOTION_ITEM` ADD CONSTRAINT `PROMOTION_ITEM_PROMOTION_ID_fkey` FOREIGN KEY (`PROMOTION_ID`) REFERENCES `PROMOTION`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PROMOTION_CUSTOMER` ADD CONSTRAINT `PROMOTION_CUSTOMER_PROMOTION_ID_fkey` FOREIGN KEY (`PROMOTION_ID`) REFERENCES `PROMOTION`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PROMOTION_CUSTOMER` ADD CONSTRAINT `PROMOTION_CUSTOMER_CUSTOMER_ID_fkey` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PROMOTION_USAGE` ADD CONSTRAINT `PROMOTION_USAGE_PROMOTION_ID_fkey` FOREIGN KEY (`PROMOTION_ID`) REFERENCES `PROMOTION`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PROMOTION_USAGE` ADD CONSTRAINT `PROMOTION_USAGE_CUSTOMER_ID_fkey` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `_USER_ROLES` ADD CONSTRAINT `_USER_ROLES_A_fkey` FOREIGN KEY (`A`) REFERENCES `ROLE`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `_USER_ROLES` ADD CONSTRAINT `_USER_ROLES_B_fkey` FOREIGN KEY (`B`) REFERENCES `USER`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
