-- AlterTable
ALTER TABLE `sales` ADD COLUMN `VOUCHER_DISCOUNT_AMOUNT` DECIMAL(15, 4) NULL,
    ADD COLUMN `VOUCHER_DISCOUNT_PERCENTAGE` DECIMAL(15, 4) NULL,
    ADD COLUMN `VOUCHER_ID` INTEGER NULL;

-- CreateTable
CREATE TABLE `reward_rule` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `TRIGGER_TYPE` VARCHAR(191) NOT NULL DEFAULT 'SPEND_MILESTONE',
    `SPEND_THRESHOLD` DECIMAL(15, 4) NOT NULL,
    `IS_REPEATABLE` BOOLEAN NOT NULL DEFAULT false,
    `DISCOUNT_TYPE` VARCHAR(191) NOT NULL,
    `DISCOUNT_PERCENTAGE` DECIMAL(15, 4) NULL,
    `DISCOUNT_AMOUNT` DECIMAL(15, 4) NULL,
    `EXPIRY_DAYS` INTEGER NOT NULL,
    `MIN_PURCHASE_AMOUNT` DECIMAL(15, 4) NULL,
    `IS_ACTIVE` BOOLEAN NOT NULL DEFAULT true,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `voucher` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `REWARD_RULE_ID` INTEGER NULL,
    `CUSTOMER_ID` INTEGER NOT NULL,
    `LOYALTY_ACCOUNT_ID` INTEGER NULL,
    `DISCOUNT_TYPE` VARCHAR(191) NOT NULL,
    `DISCOUNT_PERCENTAGE` DECIMAL(15, 4) NULL,
    `DISCOUNT_AMOUNT` DECIMAL(15, 4) NULL,
    `MIN_PURCHASE_AMOUNT` DECIMAL(15, 4) NULL,
    `STATUS` VARCHAR(191) NOT NULL DEFAULT 'ACTIVE',
    `MILESTONE_SPEND_SNAPSHOT` DECIMAL(15, 4) NULL,
    `LABEL` VARCHAR(191) NOT NULL,
    `EXPIRES_AT` DATETIME(3) NOT NULL,
    `REDEEMED_AT` DATETIME(3) NULL,
    `REDEEMED_IN_SALES_ID` INTEGER NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    UNIQUE INDEX `voucher_REDEEMED_IN_SALES_ID_key`(`REDEEMED_IN_SALES_ID`),
    INDEX `voucher_CUSTOMER_ID_STATUS_idx`(`CUSTOMER_ID`, `STATUS`),
    INDEX `voucher_EXPIRES_AT_idx`(`EXPIRES_AT`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `idempotency_record` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `KEY` VARCHAR(64) NOT NULL,
    `ENDPOINT` VARCHAR(255) NOT NULL,
    `USER_ID` INTEGER NULL,
    `RESPONSE_STATUS` INTEGER NOT NULL,
    `RESPONSE_BODY` MEDIUMTEXT NOT NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `idempotency_record_CREATED_AT_idx`(`CREATED_AT`),
    UNIQUE INDEX `idempotency_record_ENDPOINT_KEY_key`(`ENDPOINT`, `KEY`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `voucher` ADD CONSTRAINT `voucher_REWARD_RULE_ID_fkey` FOREIGN KEY (`REWARD_RULE_ID`) REFERENCES `reward_rule`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `voucher` ADD CONSTRAINT `voucher_CUSTOMER_ID_fkey` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `customer`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `voucher` ADD CONSTRAINT `voucher_LOYALTY_ACCOUNT_ID_fkey` FOREIGN KEY (`LOYALTY_ACCOUNT_ID`) REFERENCES `loyalty_account`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `voucher` ADD CONSTRAINT `voucher_REDEEMED_IN_SALES_ID_fkey` FOREIGN KEY (`REDEEMED_IN_SALES_ID`) REFERENCES `sales`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;
