-- AlterTable
ALTER TABLE `purchase_order` ADD COLUMN `QUOTATION_ID` INTEGER NULL;

-- CreateTable
CREATE TABLE `quotation` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `QUOTATION_NUMBER` VARCHAR(191) NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `SUPPLIER_ID` INTEGER NOT NULL,
    `QUOTATION_DATE` DATETIME(3) NULL,
    `VALID_UNTIL_DATE` DATETIME(3) NULL,
    `SESSION_ID` INTEGER NULL,
    `DISCOUNT_TYPE` VARCHAR(191) NULL DEFAULT '',
    `DISCOUNT_AMOUNT` DECIMAL(15, 4) NULL,
    `SERVICE_CHARGE_AMOUNT` DECIMAL(15, 4) NULL,
    `TAX_AMOUNT` DECIMAL(15, 4) NULL,
    `ROUNDING_AMOUNT` DECIMAL(15, 4) NULL,
    `SUBTOTAL_AMOUNT` DECIMAL(15, 4) NULL,
    `TOTAL_AMOUNT` DECIMAL(15, 4) NULL,
    `STATUS` VARCHAR(191) NULL,
    `REMARK` VARCHAR(191) NULL,
    `CURRENCY` VARCHAR(191) NOT NULL DEFAULT 'IDR',
    `PERFORMED_BY` VARCHAR(191) NULL DEFAULT '',
    `CONVERTED_TO_PO_AT` DATETIME(3) NULL,
    `CONVERTED_PO_ID` INTEGER NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,
    `IS_TAX_INCLUSIVE` BOOLEAN NULL DEFAULT false,

    UNIQUE INDEX `quotation_QUOTATION_NUMBER_key`(`QUOTATION_NUMBER`),
    INDEX `quotation_SUPPLIER_ID_idx`(`SUPPLIER_ID`),
    INDEX `quotation_OUTLET_ID_idx`(`OUTLET_ID`),
    INDEX `quotation_STATUS_idx`(`STATUS`),
    INDEX `quotation_QUOTATION_DATE_idx`(`QUOTATION_DATE`),
    INDEX `quotation_CREATED_AT_UPDATED_AT_DELETED_AT_idx`(`CREATED_AT`, `UPDATED_AT`, `DELETED_AT`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `quotation_item` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `QUOTATION_ID` INTEGER NOT NULL,
    `ITEM_ID` INTEGER NOT NULL,
    `QUANTITY` DECIMAL(15, 4) NOT NULL,
    `UNIT_PRICE` DECIMAL(15, 4) NOT NULL,
    `TAX_AMOUNT` DECIMAL(15, 4) NULL,
    `DISCOUNT_TYPE` VARCHAR(191) NULL DEFAULT '',
    `DISCOUNT_AMOUNT` DECIMAL(65, 30) NULL DEFAULT 0,
    `SUBTOTAL` DECIMAL(15, 4) NOT NULL,
    `REMARK` VARCHAR(191) NULL DEFAULT '',
    `LEAD_TIME` INTEGER NULL,
    `IS_ACCEPTED` BOOLEAN NULL,
    `VERSION` INTEGER NULL DEFAULT 1,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,

    INDEX `quotation_item_QUOTATION_ID_idx`(`QUOTATION_ID`),
    INDEX `quotation_item_ITEM_ID_idx`(`ITEM_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `quotation` ADD CONSTRAINT `quotation_SESSION_ID_fkey` FOREIGN KEY (`SESSION_ID`) REFERENCES `session`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `quotation` ADD CONSTRAINT `quotation_SUPPLIER_ID_fkey` FOREIGN KEY (`SUPPLIER_ID`) REFERENCES `supplier`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `quotation_item` ADD CONSTRAINT `quotation_item_QUOTATION_ID_fkey` FOREIGN KEY (`QUOTATION_ID`) REFERENCES `quotation`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `quotation_item` ADD CONSTRAINT `quotation_item_ITEM_ID_fkey` FOREIGN KEY (`ITEM_ID`) REFERENCES `item`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `purchase_order` ADD CONSTRAINT `purchase_order_QUOTATION_ID_fkey` FOREIGN KEY (`QUOTATION_ID`) REFERENCES `quotation`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;
