-- AlterTable
ALTER TABLE `delivery_order_item` ADD COLUMN `VARIANT_NAME` VARCHAR(191) NULL,
    ADD COLUMN `VARIANT_SKU` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `invoice_item` ADD COLUMN `VARIANT_NAME` VARCHAR(191) NULL,
    ADD COLUMN `VARIANT_SKU` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `purchase_order_item` ADD COLUMN `VARIANT_NAME` VARCHAR(191) NULL,
    ADD COLUMN `VARIANT_SKU` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `quotation_item` ADD COLUMN `VARIANT_NAME` VARCHAR(191) NULL,
    ADD COLUMN `VARIANT_SKU` VARCHAR(191) NULL;

-- AddForeignKey
ALTER TABLE `stock_balance` ADD CONSTRAINT `stock_balance_ITEM_ID_fkey` FOREIGN KEY (`ITEM_ID`) REFERENCES `item`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `warehouse_stock_balance` ADD CONSTRAINT `warehouse_stock_balance_ITEM_ID_fkey` FOREIGN KEY (`ITEM_ID`) REFERENCES `item`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
