-- CreateTable
CREATE TABLE `setting_definition` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `KEY` VARCHAR(191) NOT NULL,
    `CATEGORY` VARCHAR(191) NOT NULL,
    `TYPE` VARCHAR(191) NOT NULL,
    `DEFAULT_VALUE` VARCHAR(191) NULL,
    `DESCRIPTION` VARCHAR(191) NULL,
    `SCOPE` VARCHAR(191) NOT NULL,
    `IS_REQUIRED` BOOLEAN NOT NULL DEFAULT false,
    `VALIDATION_RULES` TEXT NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NOT NULL DEFAULT 1,

    UNIQUE INDEX `setting_definition_KEY_key`(`KEY`),
    INDEX `setting_definition_CATEGORY_idx`(`CATEGORY`),
    INDEX `setting_definition_SCOPE_idx`(`SCOPE`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
