-- AlterTable
ALTER TABLE `MENU_CATEGORY` MODIFY `IMAGE_URL` TEXT NULL;

-- AlterTable
ALTER TABLE `MENU_ITEM` MODIFY `IMAGE_URL` TEXT NULL;

-- AlterTable
ALTER TABLE `MENU_ITEM_MODIFIER` MODIFY `IMAGE_URL` TEXT NULL;
