-- CreateTable
CREATE TABLE `tenant_warehouse` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TENANT_ID` INTEGER NOT NULL,
    `WAREHOUSE_NAME` VARCHAR(191) NOT NULL,
    `WAREHOUSE_CODE` VARCHAR(191) NOT NULL,
    `ADDRESS` VARCHAR(191) NULL,
    `IS_ACTIVE` BOOLEAN NOT NULL DEFAULT true,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    INDEX `tenant_warehouse_TENANT_ID_idx`(`TENANT_ID`),
    INDEX `tenant_warehouse_WAREHOUSE_CODE_idx`(`WAREHOUSE_CODE`),
    INDEX `tenant_warehouse_IS_ACTIVE_idx`(`IS_ACTIVE`),
    INDEX `tenant_warehouse_IS_DELETED_idx`(`IS_DELETED`),
    UNIQUE INDEX `tenant_warehouse_TENANT_ID_WAREHOUSE_CODE_key`(`TENANT_ID`, `WAREHOUSE_CODE`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `tenant_warehouse` ADD CONSTRAINT `tenant_warehouse_TENANT_ID_fkey` FOREIGN KEY (`TENANT_ID`) REFERENCES `tenant`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
