-- CreateTable
CREATE TABLE `tenant_payment` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `INVOICE_NUMBER` VARCHAR(191) NOT NULL,
    `TENANT_ID` INTEGER NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `SUBSCRIPTION_ID` INTEGER NOT NULL,
    `AMOUNT` DOUBLE NOT NULL,
    `CURRENCY` VARCHAR(191) NOT NULL DEFAULT 'IDR',
    `PAYMENT_METHOD` VARCHAR(191) NOT NULL,
    `REFERENCE_NUMBER` VARCHAR(191) NULL,
    `NOTES` TEXT NULL,
    `PAYMENT_DATE` DATETIME(3) NOT NULL,
    `PERIOD_FROM` DATETIME(3) NOT NULL,
    `PERIOD_TO` DATETIME(3) NOT NULL,
    `PREVIOUS_VALID_UNTIL` DATETIME(3) NOT NULL,
    `EXTENSION_MONTHS` INTEGER NOT NULL DEFAULT 1,
    `COST_SNAPSHOT` JSON NOT NULL,
    `RECORDED_BY` INTEGER NULL,
    `RECORDED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `tenant_payment_INVOICE_NUMBER_key`(`INVOICE_NUMBER`),
    INDEX `tenant_payment_TENANT_ID_idx`(`TENANT_ID`),
    INDEX `tenant_payment_OUTLET_ID_idx`(`OUTLET_ID`),
    INDEX `tenant_payment_INVOICE_NUMBER_idx`(`INVOICE_NUMBER`),
    INDEX `tenant_payment_PAYMENT_DATE_idx`(`PAYMENT_DATE`),
    INDEX `tenant_payment_PERIOD_FROM_PERIOD_TO_idx`(`PERIOD_FROM`, `PERIOD_TO`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `tenant_payment` ADD CONSTRAINT `tenant_payment_TENANT_ID_fkey` FOREIGN KEY (`TENANT_ID`) REFERENCES `tenant`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `tenant_payment` ADD CONSTRAINT `tenant_payment_OUTLET_ID_fkey` FOREIGN KEY (`OUTLET_ID`) REFERENCES `tenant_outlet`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `tenant_payment` ADD CONSTRAINT `tenant_payment_SUBSCRIPTION_ID_fkey` FOREIGN KEY (`SUBSCRIPTION_ID`) REFERENCES `tenant_subscription`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
