-- AlterTable
ALTER TABLE `invoice` ADD COLUMN `INVOICE_SETTLEMENT_ID` INTEGER NULL;

-- CreateTable
CREATE TABLE `invoice_settlement` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `SETTLEMENT_NUMBER` VARCHAR(191) NOT NULL,
    `SETTLEMENT_DATE` DATETIME(3) NOT NULL,
    `SETTLEMENT_TYPE` VARCHAR(191) NOT NULL,
    `PAYMENT_METHOD` VARCHAR(191) NULL,
    `SETTLEMENT_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `CURRENCY` VARCHAR(191) NOT NULL,
    `EXCHANGE_RATE` DECIMAL(15, 8) NULL DEFAULT 1,
    `REFERENCE` VARCHAR(191) NULL,
    `REMARK` VARCHAR(191) NULL DEFAULT '',
    `STATUS` VARCHAR(191) NOT NULL DEFAULT 'COMPLETED',
    `PERFORMED_BY` VARCHAR(191) NULL DEFAULT '',
    `TOTAL_REBATE_AMOUNT` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `REBATE_REASON` VARCHAR(191) NULL,
    `TOTAL_INVOICE_COUNT` INTEGER NOT NULL DEFAULT 0,
    `TOTAL_INVOICE_AMOUNT` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    UNIQUE INDEX `invoice_settlement_SETTLEMENT_NUMBER_key`(`SETTLEMENT_NUMBER`),
    INDEX `invoice_settlement_SETTLEMENT_DATE_idx`(`SETTLEMENT_DATE`),
    INDEX `invoice_settlement_SETTLEMENT_TYPE_idx`(`SETTLEMENT_TYPE`),
    INDEX `invoice_settlement_STATUS_idx`(`STATUS`),
    INDEX `invoice_settlement_CREATED_AT_UPDATED_AT_DELETED_AT_idx`(`CREATED_AT`, `UPDATED_AT`, `DELETED_AT`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateIndex
CREATE INDEX `invoice_INVOICE_SETTLEMENT_ID_idx` ON `invoice`(`INVOICE_SETTLEMENT_ID`);

-- AddForeignKey
ALTER TABLE `invoice` ADD CONSTRAINT `invoice_INVOICE_SETTLEMENT_ID_fkey` FOREIGN KEY (`INVOICE_SETTLEMENT_ID`) REFERENCES `invoice_settlement`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;
