-- AlterTable
ALTER TABLE `sales` ADD COLUMN `STOCK_SOURCE_OUTLET_ID` INTEGER NULL,
    ADD COLUMN `STOCK_SOURCE_TYPE` VARCHAR(191) NULL,
    ADD COLUMN `STOCK_SOURCE_WAREHOUSE_ID` INTEGER NULL;

-- CreateTable
CREATE TABLE `warehouse` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TENANT_WAREHOUSE_ID` INTEGER NOT NULL,
    `WAREHOUSE_NAME` VARCHAR(191) NOT NULL,
    `WAREHOUSE_CODE` VARCHAR(191) NOT NULL,
    `STREET` VARCHAR(191) NULL,
    `CITY` VARCHAR(191) NULL,
    `STATE` VARCHAR(191) NULL,
    `POSTAL_CODE` VARCHAR(191) NULL,
    `COUNTRY` VARCHAR(191) NULL,
    `CONTACT_PHONE` VARCHAR(191) NULL,
    `CONTACT_EMAIL` VARCHAR(191) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    INDEX `warehouse_WAREHOUSE_CODE_idx`(`WAREHOUSE_CODE`),
    INDEX `warehouse_TENANT_WAREHOUSE_ID_idx`(`TENANT_WAREHOUSE_ID`),
    INDEX `warehouse_IS_DELETED_idx`(`IS_DELETED`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `warehouse_stock_balance` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ITEM_ID` INTEGER NOT NULL,
    `WAREHOUSE_ID` INTEGER NOT NULL,
    `AVAILABLE_QUANTITY` DECIMAL(15, 4) NOT NULL,
    `ON_HAND_QUANTITY` DECIMAL(15, 4) NOT NULL,
    `REORDER_THRESHOLD` DECIMAL(15, 4) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `LAST_RESTOCK_DATE` DATETIME(3) NULL,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `warehouse_stock_balance_WAREHOUSE_ID_idx`(`WAREHOUSE_ID`),
    INDEX `warehouse_stock_balance_IS_DELETED_idx`(`IS_DELETED`),
    UNIQUE INDEX `warehouse_stock_balance_ITEM_ID_WAREHOUSE_ID_REORDER_THRESHO_key`(`ITEM_ID`, `WAREHOUSE_ID`, `REORDER_THRESHOLD`, `IS_DELETED`, `AVAILABLE_QUANTITY`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `warehouse_stock_receipt` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ITEM_ID` INTEGER NOT NULL,
    `WAREHOUSE_ID` INTEGER NOT NULL,
    `DELIVERY_ORDER_ID` INTEGER NULL,
    `QUANTITY` DECIMAL(15, 4) NOT NULL,
    `AVAILABLE_QUANTITY` DECIMAL(15, 4) NOT NULL,
    `COST` DECIMAL(15, 4) NOT NULL,
    `RECEIPT_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `REMARK` VARCHAR(191) NULL DEFAULT '',
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,

    INDEX `warehouse_stock_receipt_ITEM_ID_RECEIPT_DATE_idx`(`ITEM_ID`, `RECEIPT_DATE`),
    INDEX `warehouse_stock_receipt_WAREHOUSE_ID_idx`(`WAREHOUSE_ID`),
    INDEX `warehouse_stock_receipt_IS_DELETED_idx`(`IS_DELETED`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `warehouse_stock_movement` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ITEM_ID` INTEGER NOT NULL,
    `WAREHOUSE_ID` INTEGER NOT NULL,
    `PREVIOUS_AVAILABLE_QUANTITY` DECIMAL(15, 4) NOT NULL,
    `PREVIOUS_ON_HAND_QUANTITY` DECIMAL(15, 4) NOT NULL,
    `AVAILABLE_QUANTITY_DELTA` DECIMAL(15, 4) NOT NULL,
    `ON_HAND_QUANTITY_DELTA` DECIMAL(15, 4) NOT NULL,
    `MOVEMENT_TYPE` VARCHAR(191) NOT NULL,
    `DOCUMENT_ID` INTEGER NOT NULL,
    `REASON` VARCHAR(191) NOT NULL,
    `REMARK` VARCHAR(191) NOT NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,
    `PERFORMED_BY` VARCHAR(191) NULL DEFAULT '',

    INDEX `warehouse_stock_movement_ITEM_ID_CREATED_AT_idx`(`ITEM_ID`, `CREATED_AT`),
    INDEX `warehouse_stock_movement_WAREHOUSE_ID_idx`(`WAREHOUSE_ID`),
    INDEX `warehouse_stock_movement_MOVEMENT_TYPE_idx`(`MOVEMENT_TYPE`),
    INDEX `warehouse_stock_movement_IS_DELETED_idx`(`IS_DELETED`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateIndex
CREATE INDEX `sales_STOCK_SOURCE_TYPE_idx` ON `sales`(`STOCK_SOURCE_TYPE`);

-- CreateIndex
CREATE INDEX `sales_STOCK_SOURCE_WAREHOUSE_ID_idx` ON `sales`(`STOCK_SOURCE_WAREHOUSE_ID`);

-- AddForeignKey
ALTER TABLE `warehouse_stock_balance` ADD CONSTRAINT `warehouse_stock_balance_ITEM_ID_fkey` FOREIGN KEY (`ITEM_ID`) REFERENCES `item`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `warehouse_stock_balance` ADD CONSTRAINT `warehouse_stock_balance_WAREHOUSE_ID_fkey` FOREIGN KEY (`WAREHOUSE_ID`) REFERENCES `warehouse`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `warehouse_stock_receipt` ADD CONSTRAINT `warehouse_stock_receipt_ITEM_ID_fkey` FOREIGN KEY (`ITEM_ID`) REFERENCES `item`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `warehouse_stock_receipt` ADD CONSTRAINT `warehouse_stock_receipt_WAREHOUSE_ID_fkey` FOREIGN KEY (`WAREHOUSE_ID`) REFERENCES `warehouse`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `warehouse_stock_movement` ADD CONSTRAINT `warehouse_stock_movement_ITEM_ID_fkey` FOREIGN KEY (`ITEM_ID`) REFERENCES `item`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `warehouse_stock_movement` ADD CONSTRAINT `warehouse_stock_movement_WAREHOUSE_ID_fkey` FOREIGN KEY (`WAREHOUSE_ID`) REFERENCES `warehouse`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
