-- AlterTable
ALTER TABLE `subscription_plan` ADD COLUMN `MAX_DEVICES` INTEGER NULL DEFAULT 5;

-- CreateTable
CREATE TABLE `pushy_device` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TENANT_USER_ID` INTEGER NOT NULL,
    `DEVICE_TOKEN` VARCHAR(191) NOT NULL,
    `PLATFORM` VARCHAR(191) NOT NULL,
    `DEVICE_NAME` VARCHAR(191) NULL,
    `APP_VERSION` VARCHAR(191) NULL,
    `IS_ACTIVE` BOOLEAN NOT NULL DEFAULT true,
    `LAST_ACTIVE_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    UNIQUE INDEX `pushy_device_DEVICE_TOKEN_key`(`DEVICE_TOKEN`),
    INDEX `pushy_device_TENANT_USER_ID_idx`(`TENANT_USER_ID`),
    INDEX `pushy_device_DEVICE_TOKEN_idx`(`DEVICE_TOKEN`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `pushy_subscription` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DEVICE_ID` INTEGER NOT NULL,
    `TOPIC` VARCHAR(191) NOT NULL,
    `SUBSCRIBED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `pushy_subscription_TOPIC_idx`(`TOPIC`),
    UNIQUE INDEX `pushy_subscription_DEVICE_ID_TOPIC_key`(`DEVICE_ID`, `TOPIC`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `pushy_device_allocation` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DEVICE_ID` INTEGER NOT NULL,
    `TENANT_ID` INTEGER NOT NULL,
    `SUBSCRIPTION_ID` INTEGER NULL,
    `ADD_ON_ID` INTEGER NULL,
    `ALLOCATION_TYPE` VARCHAR(191) NOT NULL DEFAULT 'included',
    `ACTIVATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `EXPIRES_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `pushy_device_allocation_DEVICE_ID_key`(`DEVICE_ID`),
    INDEX `pushy_device_allocation_TENANT_ID_idx`(`TENANT_ID`),
    INDEX `pushy_device_allocation_ALLOCATION_TYPE_idx`(`ALLOCATION_TYPE`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `pushy_device` ADD CONSTRAINT `pushy_device_TENANT_USER_ID_fkey` FOREIGN KEY (`TENANT_USER_ID`) REFERENCES `tenant_user`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `pushy_subscription` ADD CONSTRAINT `pushy_subscription_DEVICE_ID_fkey` FOREIGN KEY (`DEVICE_ID`) REFERENCES `pushy_device`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `pushy_device_allocation` ADD CONSTRAINT `pushy_device_allocation_DEVICE_ID_fkey` FOREIGN KEY (`DEVICE_ID`) REFERENCES `pushy_device`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `pushy_device_allocation` ADD CONSTRAINT `pushy_device_allocation_TENANT_ID_fkey` FOREIGN KEY (`TENANT_ID`) REFERENCES `tenant`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `pushy_device_allocation` ADD CONSTRAINT `pushy_device_allocation_SUBSCRIPTION_ID_fkey` FOREIGN KEY (`SUBSCRIPTION_ID`) REFERENCES `tenant_subscription`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;
