-- AlterTable
ALTER TABLE `tenant_subscription` ADD COLUMN `CUSTOM_PRICE` DOUBLE NULL,
    ADD COLUMN `CUSTOM_PRICE_NOTE` TEXT NULL;

-- CreateTable
CREATE TABLE `custom_price_log` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TENANT_ID` INTEGER NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `TENANT_SUBSCRIPTION_ID` INTEGER NOT NULL,
    `PREVIOUS_PRICE` DOUBLE NULL,
    `NEW_PRICE` DOUBLE NULL,
    `NOTE` TEXT NULL,
    `CHANGED_BY` INTEGER NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `custom_price_log_TENANT_ID_idx`(`TENANT_ID`),
    INDEX `custom_price_log_TENANT_SUBSCRIPTION_ID_idx`(`TENANT_SUBSCRIPTION_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tenant_add_on` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TENANT_ID` INTEGER NOT NULL,
    `ADD_ON_ID` INTEGER NOT NULL,
    `QUANTITY` INTEGER NOT NULL DEFAULT 1,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    INDEX `tenant_add_on_TENANT_ID_idx`(`TENANT_ID`),
    UNIQUE INDEX `tenant_add_on_TENANT_ID_ADD_ON_ID_key`(`TENANT_ID`, `ADD_ON_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `tenant_add_on` ADD CONSTRAINT `tenant_add_on_TENANT_ID_fkey` FOREIGN KEY (`TENANT_ID`) REFERENCES `tenant`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `tenant_add_on` ADD CONSTRAINT `tenant_add_on_ADD_ON_ID_fkey` FOREIGN KEY (`ADD_ON_ID`) REFERENCES `subscription_add_on`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
