-- CreateTable
CREATE TABLE `STOCK` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ITEM_CODE` VARCHAR(191) NOT NULL,
    `AVAILABLE_QUANTITY` DECIMAL(65, 30) NOT NULL,
    `ON_HAND_QUANTITY` DECIMAL(65, 30) NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `STOCK_CHECK` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CREATED_DATETIME` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ITEM_CODE` VARCHAR(191) NOT NULL,
    `AVAILABLE_QUANTITY` DECIMAL(65, 30) NOT NULL,
    `ON_HAND_QUANTITY` DECIMAL(65, 30) NOT NULL,
    `DOCUMENT_ID` INTEGER NOT NULL,
    `DOCUMENT_TYPE` VARCHAR(191) NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
