-- AlterTable
ALTER TABLE `sales` ADD COLUMN `CUSTOMER_SUBSCRIPTION_ID` INTEGER NULL,
    ADD COLUMN `LOYALTY_POINTS_EARNED` DECIMAL(15, 4) NULL,
    ADD COLUMN `LOYALTY_POINTS_REDEEMED` DECIMAL(15, 4) NULL,
    ADD COLUMN `LOYALTY_POINTS_REDEMPTION_VALUE` DECIMAL(15, 4) NULL,
    ADD COLUMN `LOYALTY_TIER_DISCOUNT_AMOUNT` DECIMAL(15, 4) NULL,
    ADD COLUMN `LOYALTY_TIER_DISCOUNT_PERCENT` DECIMAL(15, 4) NULL,
    ADD COLUMN `SUBSCRIPTION_DISCOUNT_AMOUNT` DECIMAL(15, 4) NULL;

-- CreateTable
CREATE TABLE `loyalty_program` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `POINTS_PER_CURRENCY` DECIMAL(15, 4) NOT NULL DEFAULT 1,
    `CURRENCY_PER_POINT` DECIMAL(15, 4) NOT NULL DEFAULT 1,
    `POINTS_EXPIRY_DAYS` INTEGER NULL,
    `MIN_REDEEM_POINTS` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `IS_ACTIVE` BOOLEAN NOT NULL DEFAULT true,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `loyalty_tier` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `LOYALTY_PROGRAM_ID` INTEGER NOT NULL,
    `NAME` VARCHAR(191) NOT NULL,
    `MIN_SPEND` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `DISCOUNT_PERCENTAGE` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `POINTS_MULTIPLIER` DECIMAL(15, 4) NOT NULL DEFAULT 1,
    `SORT_ORDER` INTEGER NOT NULL DEFAULT 0,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `loyalty_tier_LOYALTY_PROGRAM_ID_idx`(`LOYALTY_PROGRAM_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `loyalty_account` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CUSTOMER_ID` INTEGER NOT NULL,
    `LOYALTY_PROGRAM_ID` INTEGER NOT NULL,
    `CURRENT_POINTS` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `TOTAL_EARNED` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `TOTAL_REDEEMED` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `TOTAL_SPEND` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `LOYALTY_TIER_ID` INTEGER NULL,
    `IS_MANUAL_TIER` BOOLEAN NOT NULL DEFAULT false,
    `JOINED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `loyalty_account_LOYALTY_TIER_ID_idx`(`LOYALTY_TIER_ID`),
    UNIQUE INDEX `loyalty_account_CUSTOMER_ID_LOYALTY_PROGRAM_ID_key`(`CUSTOMER_ID`, `LOYALTY_PROGRAM_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `loyalty_point_batch` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `LOYALTY_ACCOUNT_ID` INTEGER NOT NULL,
    `ORIGINAL_POINTS` DECIMAL(15, 4) NOT NULL,
    `REMAINING_POINTS` DECIMAL(15, 4) NOT NULL,
    `EXPIRES_AT` DATETIME(3) NULL,
    `EARNED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `SALES_ID` INTEGER NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `loyalty_point_batch_LOYALTY_ACCOUNT_ID_EXPIRES_AT_idx`(`LOYALTY_ACCOUNT_ID`, `EXPIRES_AT`),
    INDEX `loyalty_point_batch_EXPIRES_AT_REMAINING_POINTS_idx`(`EXPIRES_AT`, `REMAINING_POINTS`),
    INDEX `loyalty_point_batch_SALES_ID_idx`(`SALES_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `loyalty_transaction` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `LOYALTY_ACCOUNT_ID` INTEGER NOT NULL,
    `TYPE` VARCHAR(191) NOT NULL,
    `POINTS` DECIMAL(15, 4) NOT NULL,
    `BALANCE_AFTER` DECIMAL(15, 4) NOT NULL,
    `SALES_ID` INTEGER NULL,
    `POINT_BATCH_ID` INTEGER NULL,
    `DESCRIPTION` VARCHAR(191) NULL,
    `PERFORMED_BY` VARCHAR(191) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `loyalty_transaction_LOYALTY_ACCOUNT_ID_CREATED_AT_idx`(`LOYALTY_ACCOUNT_ID`, `CREATED_AT`),
    UNIQUE INDEX `loyalty_transaction_SALES_ID_TYPE_key`(`SALES_ID`, `TYPE`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `subscription_package` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `PACKAGE_TYPE` VARCHAR(191) NOT NULL,
    `PRICE` DECIMAL(15, 4) NOT NULL,
    `TOTAL_QUOTA` INTEGER NULL,
    `QUOTA_UNIT` VARCHAR(191) NULL,
    `DURATION_DAYS` INTEGER NULL,
    `DISCOUNT_PERCENTAGE` DECIMAL(15, 4) NULL,
    `DISCOUNT_AMOUNT` DECIMAL(15, 4) NULL,
    `VALIDITY_DAYS` INTEGER NULL,
    `IS_ACTIVE` BOOLEAN NOT NULL DEFAULT true,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `subscription_package_category` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `SUBSCRIPTION_PACKAGE_ID` INTEGER NOT NULL,
    `CATEGORY_ID` INTEGER NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,

    UNIQUE INDEX `subscription_package_category_SUBSCRIPTION_PACKAGE_ID_CATEGO_key`(`SUBSCRIPTION_PACKAGE_ID`, `CATEGORY_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `customer_subscription` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CUSTOMER_ID` INTEGER NOT NULL,
    `SUBSCRIPTION_PACKAGE_ID` INTEGER NOT NULL,
    `STATUS` VARCHAR(191) NOT NULL DEFAULT 'ACTIVE',
    `START_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `END_DATE` DATETIME(3) NULL,
    `REMAINING_QUOTA` INTEGER NULL,
    `USED_QUOTA` INTEGER NOT NULL DEFAULT 0,
    `PAID_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `PACKAGE_SNAPSHOT` JSON NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `customer_subscription_CUSTOMER_ID_STATUS_idx`(`CUSTOMER_ID`, `STATUS`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `subscription_usage` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CUSTOMER_SUBSCRIPTION_ID` INTEGER NOT NULL,
    `SALES_ID` INTEGER NOT NULL,
    `QUANTITY_USED` INTEGER NOT NULL DEFAULT 1,
    `REMAINING_AFTER` INTEGER NOT NULL,
    `PERFORMED_BY` VARCHAR(191) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `subscription_usage_CUSTOMER_SUBSCRIPTION_ID_CREATED_AT_idx`(`CUSTOMER_SUBSCRIPTION_ID`, `CREATED_AT`),
    UNIQUE INDEX `subscription_usage_SALES_ID_CUSTOMER_SUBSCRIPTION_ID_key`(`SALES_ID`, `CUSTOMER_SUBSCRIPTION_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateIndex
CREATE INDEX `sales_CUSTOMER_SUBSCRIPTION_ID_idx` ON `sales`(`CUSTOMER_SUBSCRIPTION_ID`);

-- AddForeignKey
ALTER TABLE `sales` ADD CONSTRAINT `sales_CUSTOMER_SUBSCRIPTION_ID_fkey` FOREIGN KEY (`CUSTOMER_SUBSCRIPTION_ID`) REFERENCES `customer_subscription`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `loyalty_tier` ADD CONSTRAINT `loyalty_tier_LOYALTY_PROGRAM_ID_fkey` FOREIGN KEY (`LOYALTY_PROGRAM_ID`) REFERENCES `loyalty_program`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `loyalty_account` ADD CONSTRAINT `loyalty_account_CUSTOMER_ID_fkey` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `customer`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `loyalty_account` ADD CONSTRAINT `loyalty_account_LOYALTY_PROGRAM_ID_fkey` FOREIGN KEY (`LOYALTY_PROGRAM_ID`) REFERENCES `loyalty_program`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `loyalty_account` ADD CONSTRAINT `loyalty_account_LOYALTY_TIER_ID_fkey` FOREIGN KEY (`LOYALTY_TIER_ID`) REFERENCES `loyalty_tier`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `loyalty_point_batch` ADD CONSTRAINT `loyalty_point_batch_LOYALTY_ACCOUNT_ID_fkey` FOREIGN KEY (`LOYALTY_ACCOUNT_ID`) REFERENCES `loyalty_account`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `loyalty_point_batch` ADD CONSTRAINT `loyalty_point_batch_SALES_ID_fkey` FOREIGN KEY (`SALES_ID`) REFERENCES `sales`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `loyalty_transaction` ADD CONSTRAINT `loyalty_transaction_LOYALTY_ACCOUNT_ID_fkey` FOREIGN KEY (`LOYALTY_ACCOUNT_ID`) REFERENCES `loyalty_account`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `loyalty_transaction` ADD CONSTRAINT `loyalty_transaction_SALES_ID_fkey` FOREIGN KEY (`SALES_ID`) REFERENCES `sales`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `subscription_package_category` ADD CONSTRAINT `subscription_package_category_SUBSCRIPTION_PACKAGE_ID_fkey` FOREIGN KEY (`SUBSCRIPTION_PACKAGE_ID`) REFERENCES `subscription_package`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `subscription_package_category` ADD CONSTRAINT `subscription_package_category_CATEGORY_ID_fkey` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `item_category`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `customer_subscription` ADD CONSTRAINT `customer_subscription_CUSTOMER_ID_fkey` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `customer`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `customer_subscription` ADD CONSTRAINT `customer_subscription_SUBSCRIPTION_PACKAGE_ID_fkey` FOREIGN KEY (`SUBSCRIPTION_PACKAGE_ID`) REFERENCES `subscription_package`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `subscription_usage` ADD CONSTRAINT `subscription_usage_CUSTOMER_SUBSCRIPTION_ID_fkey` FOREIGN KEY (`CUSTOMER_SUBSCRIPTION_ID`) REFERENCES `customer_subscription`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `subscription_usage` ADD CONSTRAINT `subscription_usage_SALES_ID_fkey` FOREIGN KEY (`SALES_ID`) REFERENCES `sales`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
