-- CreateTable
CREATE TABLE `role` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `CATEGORY` VARCHAR(191) NULL,
    `DESCRIPTION` VARCHAR(191) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    UNIQUE INDEX `role_NAME_key`(`NAME`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `role_permission` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ROLE_ID` INTEGER NOT NULL,
    `PERMISSION_ID` INTEGER NOT NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    UNIQUE INDEX `role_permission_ROLE_ID_PERMISSION_ID_key`(`ROLE_ID`, `PERMISSION_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `user` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USERNAME` VARCHAR(191) NOT NULL,
    `PASSWORD` VARCHAR(191) NOT NULL,
    `OVERRIDE_PIN` VARCHAR(191) NULL,
    `LAST_NAME` VARCHAR(191) NULL,
    `FIRST_NAME` VARCHAR(191) NULL,
    `MOBILE` VARCHAR(191) NULL,
    `EMAIL` VARCHAR(191) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    UNIQUE INDEX `user_USERNAME_key`(`USERNAME`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `override_log` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USER_ID` INTEGER NOT NULL,
    `APPROVER_ID` INTEGER NOT NULL,
    `ACTION` VARCHAR(191) NOT NULL,
    `REASON` VARCHAR(191) NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `setting` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TENANT_ID` INTEGER NULL,
    `USER_ID` INTEGER NULL,
    `OUTLET_ID` INTEGER NULL,
    `KEY` VARCHAR(191) NOT NULL,
    `VALUE` VARCHAR(191) NOT NULL,
    `TYPE` ENUM('INT', 'STRING', 'BOOLEAN', 'JSON') NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `setting_KEY_idx`(`KEY`),
    UNIQUE INDEX `setting_TENANT_ID_USER_ID_OUTLET_ID_KEY_key`(`TENANT_ID`, `USER_ID`, `OUTLET_ID`, `KEY`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `referral` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USER_ID` INTEGER NOT NULL,
    `REFERRAL_ID` INTEGER NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `supplier` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `COMPANY_NAME` VARCHAR(191) NOT NULL,
    `COMPANY_STREET` VARCHAR(191) NULL,
    `COMPANY_CITY` VARCHAR(191) NULL,
    `COMPANY_STATE` VARCHAR(191) NULL,
    `COMPANY_POSTAL_CODE` VARCHAR(191) NULL,
    `COMPANY_COUNTRY` VARCHAR(191) NULL,
    `COMPANY_REGISTRATION_NUMBER` VARCHAR(191) NULL,
    `PERSON_IN_CHARGE_LAST_NAME` VARCHAR(191) NULL,
    `PERSON_IN_CHARGE_FIRST_NAME` VARCHAR(191) NULL,
    `MOBILE` VARCHAR(191) NULL,
    `EMAIL` VARCHAR(191) NULL,
    `REMARK` VARCHAR(191) NULL,
    `HAS_TAX` BOOLEAN NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    UNIQUE INDEX `supplier_COMPANY_NAME_key`(`COMPANY_NAME`),
    INDEX `supplier_COMPANY_NAME_idx`(`COMPANY_NAME`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `customer` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `SALUTATION` VARCHAR(191) NOT NULL DEFAULT '',
    `LAST_NAME` VARCHAR(191) NOT NULL,
    `FIRST_NAME` VARCHAR(191) NOT NULL,
    `MOBILE` VARCHAR(191) NULL,
    `EMAIL` VARCHAR(191) NULL,
    `GENDER` VARCHAR(191) NULL,
    `BILL_STREET` VARCHAR(191) NULL,
    `BILL_CITY` VARCHAR(191) NULL,
    `BILL_STATE` VARCHAR(191) NULL,
    `BILL_POSTAL_CODE` VARCHAR(191) NULL,
    `BILL_COUNTRY` VARCHAR(191) NULL,
    `BILL_REMARK` VARCHAR(191) NULL,
    `SHIP_STREET` VARCHAR(191) NULL,
    `SHIP_CITY` VARCHAR(191) NULL,
    `SHIP_STATE` VARCHAR(191) NULL,
    `SHIP_POSTAL_CODE` VARCHAR(191) NULL,
    `SHIP_COUNTRY` VARCHAR(191) NULL,
    `SHIP_REMARK` VARCHAR(191) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `company` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `COMPANY_NAME` VARCHAR(191) NOT NULL DEFAULT '',
    `STREET` VARCHAR(191) NOT NULL DEFAULT '',
    `CITY` VARCHAR(191) NOT NULL DEFAULT '',
    `STATE` VARCHAR(191) NOT NULL DEFAULT '',
    `POSTAL_CODE` VARCHAR(191) NOT NULL DEFAULT '',
    `COUNTRY` VARCHAR(191) NOT NULL DEFAULT '',
    `REGISTRATION_NUMBER` VARCHAR(191) NOT NULL,
    `WEBSITE` VARCHAR(191) NOT NULL DEFAULT '',
    `REFERRAL_ID` VARCHAR(191) NOT NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    UNIQUE INDEX `company_REGISTRATION_NUMBER_key`(`REGISTRATION_NUMBER`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `outlet` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TENANT_OUTLET_ID` INTEGER NOT NULL,
    `OUTLET_NAME` VARCHAR(191) NOT NULL,
    `STREET` VARCHAR(191) NOT NULL DEFAULT '',
    `CITY` VARCHAR(191) NOT NULL DEFAULT '',
    `STATE` VARCHAR(191) NOT NULL DEFAULT '',
    `POSTAL_CODE` VARCHAR(191) NOT NULL DEFAULT '',
    `COUNTRY` VARCHAR(191) NOT NULL DEFAULT '',
    `OUTLET_TEL` VARCHAR(191) NOT NULL DEFAULT '',
    `OUTLET_EMAIL` VARCHAR(191) NOT NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `item` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ITEM_NAME` VARCHAR(191) NOT NULL,
    `ITEM_CODE` VARCHAR(191) NOT NULL,
    `ITEM_TYPE` VARCHAR(191) NOT NULL DEFAULT '',
    `ITEM_MODEL` VARCHAR(191) NOT NULL DEFAULT '',
    `ITEM_BRAND` VARCHAR(191) NOT NULL DEFAULT '',
    `ITEM_DESCRIPTION` VARCHAR(191) NULL DEFAULT '',
    `CATEGORY_ID` INTEGER NOT NULL,
    `COST` DECIMAL(15, 4) NOT NULL,
    `PRICE` DECIMAL(15, 4) NOT NULL,
    `CURRENCY` VARCHAR(191) NOT NULL DEFAULT 'IDR',
    `IS_OPEN_PRICE` BOOLEAN NULL DEFAULT false,
    `UNIT_OF_MEASURE` VARCHAR(191) NOT NULL DEFAULT '',
    `HEIGHT` DOUBLE NULL DEFAULT 0,
    `WIDTH` DOUBLE NULL DEFAULT 0,
    `LENGTH` DOUBLE NULL DEFAULT 0,
    `WEIGHT` DOUBLE NULL DEFAULT 0,
    `ALTERNATE_LOOKUP` VARCHAR(191) NULL DEFAULT '',
    `IMAGE` VARCHAR(191) NULL DEFAULT '',
    `HAS_TAX` BOOLEAN NULL,
    `TAX_RATE` DOUBLE NULL,
    `SUPPLIER_ID` INTEGER NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `item_CREATED_AT_idx`(`CREATED_AT`),
    INDEX `item_DELETED_AT_idx`(`DELETED_AT`),
    INDEX `item_CATEGORY_ID_idx`(`CATEGORY_ID`),
    INDEX `item_UPDATED_AT_idx`(`UPDATED_AT`),
    INDEX `item_SUPPLIER_ID_idx`(`SUPPLIER_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `item_category` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `DESCRIPTION` VARCHAR(191) NULL DEFAULT '',
    `PARENT_ID` INTEGER NULL,
    `IMAGE` VARCHAR(191) NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    UNIQUE INDEX `item_category_NAME_key`(`NAME`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `sales` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `OUTLET_ID` INTEGER NOT NULL,
    `BUSINESS_DATE` DATETIME(3) NOT NULL,
    `SALES_TYPE` VARCHAR(191) NOT NULL,
    `CUSTOMER_NAME` VARCHAR(191) NULL DEFAULT '',
    `CUSTOMER_ID` INTEGER NULL,
    `PHONE_NUMBER` VARCHAR(191) NULL DEFAULT '',
    `BILL_STREET` VARCHAR(191) NOT NULL DEFAULT '',
    `BILL_CITY` VARCHAR(191) NOT NULL DEFAULT '',
    `BILL_STATE` VARCHAR(191) NOT NULL DEFAULT '',
    `BILL_POSTAL_CODE` VARCHAR(191) NOT NULL DEFAULT '',
    `BILL_COUNTRY` VARCHAR(191) NOT NULL DEFAULT '',
    `SHIP_STREET` VARCHAR(191) NOT NULL DEFAULT '',
    `SHIP_CITY` VARCHAR(191) NOT NULL DEFAULT '',
    `SHIP_STATE` VARCHAR(191) NOT NULL DEFAULT '',
    `SHIP_POSTAL_CODE` VARCHAR(191) NOT NULL DEFAULT '',
    `SHIP_COUNTRY` VARCHAR(191) NOT NULL DEFAULT '',
    `TOTAL_ITEM_DISCOUNT_AMOUNT` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `DISCOUNT_PERCENTAGE` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `DISCOUNT_AMOUNT` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `PROFIT_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `SERVICE_CHARGE_AMOUNT` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `TAX_AMOUNT` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `ROUNDING_AMOUNT` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `SUBTOTAL_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `TOTAL_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `PAID_AMOUNT` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `CHANGE_AMOUNT` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `STATUS` VARCHAR(191) NOT NULL,
    `REMARK` VARCHAR(191) NOT NULL DEFAULT '',
    `COMPLETED_SESSION_ID` INTEGER NULL,
    `SESSION_ID` INTEGER NOT NULL,
    `EOD_ID` INTEGER NOT NULL,
    `SALES_QUOTATION_ID` INTEGER NOT NULL DEFAULT 0,
    `PERFORMED_BY` VARCHAR(191) NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,
    `TABLE_ID` INTEGER NULL,
    `ORDER_STATUS` VARCHAR(191) NULL,

    INDEX `sales_BUSINESS_DATE_idx`(`BUSINESS_DATE`),
    INDEX `sales_OUTLET_ID_idx`(`OUTLET_ID`),
    INDEX `sales_SESSION_ID_COMPLETED_SESSION_ID_idx`(`SESSION_ID`, `COMPLETED_SESSION_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `sales_item` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `SALES_ID` INTEGER NOT NULL,
    `ITEM_ID` INTEGER NOT NULL,
    `ITEM_NAME` VARCHAR(191) NOT NULL,
    `ITEM_CODE` VARCHAR(191) NOT NULL,
    `ITEM_BRAND` VARCHAR(191) NOT NULL,
    `ITEM_MODEL` VARCHAR(191) NOT NULL DEFAULT '',
    `QUANTITY` DECIMAL(15, 4) NOT NULL,
    `COST` DECIMAL(15, 4) NOT NULL,
    `PRICE` DECIMAL(15, 4) NOT NULL,
    `PRICE_BEFORE_TAX` DECIMAL(15, 4) NOT NULL,
    `PROFIT` DECIMAL(15, 4) NOT NULL,
    `DISCOUNT_PERCENTAGE` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `DISCOUNT_AMOUNT` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `SERVICE_CHARGE_AMOUNT` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `TAX_AMOUNT` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `SUBTOTAL_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `REMARK` VARCHAR(191) NOT NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,
    `SPECIAL_INSTRUCTIONS` VARCHAR(191) NULL DEFAULT '',
    `ITEM_STATUS` VARCHAR(191) NULL,
    `PRIORITY` VARCHAR(191) NULL,
    `ESTIMATED_PREP_TIME` INTEGER NULL,

    INDEX `sales_item_ITEM_STATUS_idx`(`ITEM_STATUS`),
    INDEX `sales_item_ITEM_ID_idx`(`ITEM_ID`),
    INDEX `sales_item_QUANTITY_idx`(`QUANTITY`),
    INDEX `sales_item_PROFIT_idx`(`PROFIT`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `sales_item_modifier` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `SALES_ITEM_ID` INTEGER NOT NULL,
    `MENU_ITEM_MODIFIER_ID` INTEGER NOT NULL,
    `ITEM_ID` INTEGER NULL,
    `MODIFIER_NAME` VARCHAR(191) NOT NULL,
    `MODIFIER_PRICE` DECIMAL(15, 4) NOT NULL,
    `QUANTITY` INTEGER NOT NULL DEFAULT 1,
    `STATUS` ENUM('ORDERED', 'PREPARING', 'SERVED', 'DELIVERED', 'CANCELLED') NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `sales_item_modifier_SALES_ITEM_ID_idx`(`SALES_ITEM_ID`),
    INDEX `sales_item_modifier_MENU_ITEM_MODIFIER_ID_idx`(`MENU_ITEM_MODIFIER_ID`),
    INDEX `sales_item_modifier_ITEM_ID_idx`(`ITEM_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `sales_quotation` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `OUTLET_ID` INTEGER NOT NULL,
    `CUSTOMER_ID` INTEGER NULL,
    `CUSTOMER_STREET` VARCHAR(191) NULL,
    `CUSTOMER_CITY` VARCHAR(191) NULL,
    `CUSTOMER_STATE` VARCHAR(191) NULL,
    `CUSTOMER_POSTAL_CODE` VARCHAR(191) NULL,
    `CUSTOMER_COUNTRY` VARCHAR(191) NULL,
    `DISCOUNT_PERCENTAGE` DECIMAL(15, 4) NOT NULL DEFAULT 0,
    `DISCOUNT_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `SERVICE_CHARGE_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `TAX_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `ROUNDING_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `SUBTOTAL_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `TOTAL_AMOUNT` DECIMAL(65, 30) NOT NULL,
    `STATUS` VARCHAR(191) NOT NULL,
    `REMARK` VARCHAR(191) NULL,
    `PERFORMED_BY` VARCHAR(191) NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `sales_quotation_item` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `SALES_QUOTATION_ID` INTEGER NOT NULL,
    `ITEM_ID` INTEGER NOT NULL,
    `QUANTITY` DECIMAL(15, 4) NOT NULL,
    `REMARK` VARCHAR(191) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `invoice` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `INVOICE_NUMBER` VARCHAR(191) NOT NULL,
    `TAX_INVOICE_NUMBER` VARCHAR(191) NOT NULL,
    `PURCHASE_ORDER_ID` INTEGER NULL,
    `SUPPLIER_ID` INTEGER NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `SUBTOTAL_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `TAX_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `SESSION_ID` INTEGER NULL,
    `DISCOUNT_TYPE` VARCHAR(191) NULL DEFAULT '',
    `DISCOUNT_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `TOTAL_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `CURRENCY` VARCHAR(191) NOT NULL,
    `STATUS` VARCHAR(191) NOT NULL,
    `INVOICE_DATE` DATETIME(3) NULL,
    `PAYMENT_DATE` DATETIME(3) NULL,
    `DUE_DATE` DATETIME(3) NULL,
    `REMARK` VARCHAR(191) NULL DEFAULT '',
    `PERFORMED_BY` VARCHAR(191) NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    UNIQUE INDEX `invoice_INVOICE_NUMBER_key`(`INVOICE_NUMBER`),
    INDEX `invoice_PURCHASE_ORDER_ID_idx`(`PURCHASE_ORDER_ID`),
    INDEX `invoice_SUPPLIER_ID_idx`(`SUPPLIER_ID`),
    INDEX `invoice_OUTLET_ID_idx`(`OUTLET_ID`),
    INDEX `invoice_CREATED_AT_UPDATED_AT_DELETED_AT_idx`(`CREATED_AT`, `UPDATED_AT`, `DELETED_AT`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `invoice_item` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `INVOICE_ID` INTEGER NOT NULL,
    `ITEM_ID` INTEGER NOT NULL,
    `QUANTITY` DECIMAL(15, 4) NOT NULL,
    `UNIT_PRICE` DECIMAL(15, 4) NOT NULL,
    `DISCOUNT_TYPE` VARCHAR(191) NULL DEFAULT '',
    `DISCOUNT_AMOUNT` DECIMAL(65, 30) NULL DEFAULT 0,
    `TAX_AMOUNT` DECIMAL(15, 4) NULL,
    `SUBTOTAL` DECIMAL(15, 4) NOT NULL,
    `REMARK` VARCHAR(191) NULL DEFAULT '',
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `invoice_item_INVOICE_ID_idx`(`INVOICE_ID`),
    INDEX `invoice_item_ITEM_ID_idx`(`ITEM_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `delivery_order` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TRACKING_NUMBER` VARCHAR(191) NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `CUSTOMER_ID` INTEGER NULL,
    `PURCHASE_ORDER_ID` INTEGER NULL,
    `SUPPLIER_ID` INTEGER NULL,
    `INVOICE_ID` INTEGER NULL,
    `SESSION_ID` INTEGER NULL,
    `DELIVERY_DATE` DATETIME(3) NULL,
    `DELIVERY_STREET` VARCHAR(191) NULL,
    `DELIVERY_CITY` VARCHAR(191) NULL,
    `DELIVERY_STATE` VARCHAR(191) NULL,
    `DELIVERY_POSTAL_CODE` VARCHAR(191) NULL,
    `DELIVERY_COUNTRY` VARCHAR(191) NULL,
    `STATUS` VARCHAR(191) NOT NULL,
    `REMARK` VARCHAR(191) NULL,
    `PERFORMED_BY` VARCHAR(191) NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `delivery_order_OUTLET_ID_idx`(`OUTLET_ID`),
    INDEX `delivery_order_CUSTOMER_ID_idx`(`CUSTOMER_ID`),
    INDEX `delivery_order_PURCHASE_ORDER_ID_idx`(`PURCHASE_ORDER_ID`),
    INDEX `delivery_order_INVOICE_ID_SUPPLIER_ID_idx`(`INVOICE_ID`, `SUPPLIER_ID`),
    INDEX `delivery_order_CREATED_AT_UPDATED_AT_DELETED_AT_idx`(`CREATED_AT`, `UPDATED_AT`, `DELETED_AT`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `delivery_order_item` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DELIVERY_ORDER_ID` INTEGER NOT NULL,
    `ITEM_ID` INTEGER NOT NULL,
    `ORDERED_QUANTITY` DOUBLE NOT NULL,
    `RECEIVED_QUANTITY` DOUBLE NOT NULL,
    `UNIT_PRICE` DECIMAL(15, 4) NULL DEFAULT 0,
    `DELIVERY_FEE` DECIMAL(15, 4) NULL DEFAULT 0,
    `REMARK` VARCHAR(191) NULL DEFAULT '',
    `VERSION` INTEGER NULL DEFAULT 1,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,

    INDEX `delivery_order_item_DELIVERY_ORDER_ID_idx`(`DELIVERY_ORDER_ID`),
    INDEX `delivery_order_item_ITEM_ID_idx`(`ITEM_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `purchase_order` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PURCHASE_ORDER_NUMBER` VARCHAR(191) NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `SUPPLIER_ID` INTEGER NOT NULL,
    `PURCHASE_ORDER_DATE` DATETIME(3) NULL,
    `SESSION_ID` INTEGER NULL,
    `DISCOUNT_TYPE` VARCHAR(191) NULL DEFAULT '',
    `DISCOUNT_AMOUNT` DECIMAL(15, 4) NULL,
    `SERVICE_CHARGE_AMOUNT` DECIMAL(15, 4) NULL,
    `TAX_AMOUNT` DECIMAL(15, 4) NULL,
    `ROUNDING_AMOUNT` DECIMAL(15, 4) NULL,
    `SUBTOTAL_AMOUNT` DECIMAL(15, 4) NULL,
    `TOTAL_AMOUNT` DECIMAL(15, 4) NULL,
    `STATUS` VARCHAR(191) NOT NULL,
    `REMARK` VARCHAR(191) NULL,
    `CURRENCY` VARCHAR(191) NOT NULL DEFAULT 'IDR',
    `PERFORMED_BY` VARCHAR(191) NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    UNIQUE INDEX `purchase_order_PURCHASE_ORDER_NUMBER_key`(`PURCHASE_ORDER_NUMBER`),
    INDEX `purchase_order_SUPPLIER_ID_idx`(`SUPPLIER_ID`),
    INDEX `purchase_order_OUTLET_ID_idx`(`OUTLET_ID`),
    INDEX `purchase_order_CREATED_AT_UPDATED_AT_DELETED_AT_idx`(`CREATED_AT`, `UPDATED_AT`, `DELETED_AT`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `purchase_order_item` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PURCHASE_ORDER_ID` INTEGER NOT NULL,
    `ITEM_ID` INTEGER NOT NULL,
    `QUANTITY` DECIMAL(15, 4) NOT NULL,
    `TAX_AMOUNT` DECIMAL(15, 4) NULL,
    `DISCOUNT_TYPE` VARCHAR(191) NULL DEFAULT '',
    `DISCOUNT_AMOUNT` DECIMAL(65, 30) NULL DEFAULT 0,
    `UNIT_PRICE` DECIMAL(15, 4) NOT NULL,
    `SUBTOTAL` DECIMAL(15, 4) NOT NULL,
    `REMARK` VARCHAR(191) NULL DEFAULT '',
    `VERSION` INTEGER NULL DEFAULT 1,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,

    INDEX `purchase_order_item_PURCHASE_ORDER_ID_idx`(`PURCHASE_ORDER_ID`),
    INDEX `purchase_order_item_ITEM_ID_idx`(`ITEM_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `payment` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PAYMENT` VARCHAR(191) NOT NULL,
    `TENDERED_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `PAID_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `CURRENCY_SYMBOL` VARCHAR(191) NOT NULL DEFAULT '',
    `SALES_ID` INTEGER NOT NULL,
    `REFERENCE` VARCHAR(191) NOT NULL DEFAULT '',
    `REMARK` VARCHAR(191) NOT NULL DEFAULT '',
    `BUSINESS_DATE` DATETIME(3) NOT NULL,
    `STATUS` VARCHAR(191) NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `SESSION_ID` INTEGER NOT NULL,
    `EOD_ID` INTEGER NOT NULL,
    `PERFORMED_BY` VARCHAR(191) NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `payment_PAYMENT_idx`(`PAYMENT`),
    INDEX `payment_BUSINESS_DATE_idx`(`BUSINESS_DATE`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `register_log` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TYPE` VARCHAR(191) NOT NULL,
    `MODIFIED_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `CURRENCY_SYMBOL` VARCHAR(191) NOT NULL DEFAULT '',
    `SALES_ID` INTEGER NOT NULL,
    `REMARK` VARCHAR(191) NOT NULL DEFAULT '',
    `STATUS` VARCHAR(191) NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `SESSION_ID` INTEGER NOT NULL,
    `EOD_ID` INTEGER NOT NULL,
    `PERFORMED_BY` VARCHAR(191) NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `card_info` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PAYMENT_ID` INTEGER NOT NULL,
    `CARD_NUMBER` VARCHAR(191) NULL,
    `CARD_EXPIRY` VARCHAR(191) NULL,
    `TRACE_NUMBER` VARCHAR(191) NULL,
    `TYPE_2` VARCHAR(191) NULL,
    `TYPE_3` VARCHAR(191) NULL,
    `CARD_RATE` DOUBLE NULL,
    `APP_CODE` VARCHAR(191) NULL,
    `CARD_TYPE` VARCHAR(191) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `session` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `OUTLET_ID` INTEGER NOT NULL,
    `BUSINESS_DATE` DATETIME(3) NOT NULL,
    `OPENING_DATE_TIME` DATETIME(3) NULL,
    `CLOSING_DATE_TIME` DATETIME(3) NULL,
    `OPENING_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `TOTAL_SALES_COUNT` INTEGER NOT NULL,
    `OPEN_BY_USER_ID` INTEGER NOT NULL,
    `CLOSE_BY_USER_ID` INTEGER NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `declaration` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PAYMENT_TYPE` VARCHAR(191) NOT NULL,
    `TOTAL_PAYMENT_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `DECLARATION_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `DIFFERENCE_AMOUNT` DECIMAL(15, 4) NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,
    `SESSION_ID` INTEGER NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `stock_balance` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ITEM_ID` INTEGER NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `AVAILABLE_QUANTITY` DECIMAL(15, 4) NOT NULL,
    `ON_HAND_QUANTITY` DECIMAL(15, 4) NOT NULL,
    `REORDER_THRESHOLD` DECIMAL(15, 4) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `LAST_RESTOCK_DATE` DATETIME(3) NULL,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    UNIQUE INDEX `stock_balance_ITEM_ID_OUTLET_ID_REORDER_THRESHOLD_IS_DELETED_key`(`ITEM_ID`, `OUTLET_ID`, `REORDER_THRESHOLD`, `IS_DELETED`, `AVAILABLE_QUANTITY`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `stock_receipt` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ITEM_ID` INTEGER NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `QUANTITY` DECIMAL(15, 4) NOT NULL,
    `COST` DECIMAL(15, 4) NOT NULL,
    `RECEIPT_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `stock_receipt_archive` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ITEM_ID` INTEGER NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `QUANTITY` DECIMAL(15, 4) NOT NULL,
    `COST` DECIMAL(15, 4) NOT NULL,
    `RECEIPT_DATE` DATETIME(3) NOT NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `stock_receipt_archive_ITEM_ID_RECEIPT_DATE_idx`(`ITEM_ID`, `RECEIPT_DATE`),
    INDEX `stock_receipt_archive_OUTLET_ID_idx`(`OUTLET_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `stock_movement` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ITEM_ID` INTEGER NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `PREVIOUS_AVAILABLE_QUANTITY` DECIMAL(15, 4) NOT NULL,
    `PREVIOUS_ON_HAND_QUANTITY` DECIMAL(15, 4) NOT NULL,
    `AVAILABLE_QUANTITY_DELTA` DECIMAL(15, 4) NOT NULL,
    `ON_HAND_QUANTITY_DELTA` DECIMAL(15, 4) NOT NULL,
    `MOVEMENT_TYPE` VARCHAR(191) NOT NULL,
    `DOCUMENT_ID` INTEGER NOT NULL,
    `REASON` VARCHAR(191) NOT NULL,
    `REMARK` VARCHAR(191) NOT NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,
    `PERFORMED_BY` VARCHAR(191) NULL DEFAULT '',

    INDEX `stock_movement_ITEM_ID_CREATED_AT_idx`(`ITEM_ID`, `CREATED_AT`),
    INDEX `stock_movement_OUTLET_ID_idx`(`OUTLET_ID`),
    INDEX `stock_movement_MOVEMENT_TYPE_idx`(`MOVEMENT_TYPE`),
    INDEX `stock_movement_IS_DELETED_idx`(`IS_DELETED`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `stock_movement_archive` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ITEM_ID` INTEGER NOT NULL,
    `ITEM_CODE` VARCHAR(191) NOT NULL,
    `ITEM_NAME` VARCHAR(191) NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `OUTLET_NAME` VARCHAR(191) NOT NULL,
    `PREVIOUS_AVAILABLE_QUANTITY` DECIMAL(15, 4) NOT NULL,
    `PREVIOUS_ON_HAND_QUANTITY` DECIMAL(15, 4) NOT NULL,
    `AVAILABLE_QUANTITY_DELTA` DECIMAL(15, 4) NOT NULL,
    `ON_HAND_QUANTITY_DELTA` DECIMAL(15, 4) NOT NULL,
    `MOVEMENT_TYPE` VARCHAR(191) NOT NULL,
    `DOCUMENT_ID` INTEGER NOT NULL,
    `DOCUMENT_TYPE` VARCHAR(191) NOT NULL,
    `REASON` VARCHAR(191) NOT NULL,
    `REMARK` VARCHAR(191) NOT NULL DEFAULT '',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `stock_movement_archive_ITEM_ID_CREATED_AT_idx`(`ITEM_ID`, `CREATED_AT`),
    INDEX `stock_movement_archive_OUTLET_ID_idx`(`OUTLET_ID`),
    INDEX `stock_movement_archive_MOVEMENT_TYPE_idx`(`MOVEMENT_TYPE`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `stock_snapshot` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ITEM_ID` INTEGER NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `AVAILABLE_QUANTITY` DECIMAL(15, 4) NOT NULL,
    `ON_HAND_QUANTITY` DECIMAL(15, 4) NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `stock_snapshot_ITEM_ID_CREATED_AT_idx`(`ITEM_ID`, `CREATED_AT`),
    INDEX `stock_snapshot_OUTLET_ID_idx`(`OUTLET_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `menu_profile_outlet` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `OUTLET_ID` INTEGER NOT NULL,
    `MENU_PROFILE_ID` INTEGER NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `menu_profile` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `DATE_START` VARCHAR(191) NOT NULL,
    `DATE_END` VARCHAR(191) NOT NULL,
    `TIME_START` VARCHAR(191) NOT NULL,
    `TIME_END` VARCHAR(191) NOT NULL,
    `IS_MONDAY` BOOLEAN NOT NULL,
    `IS_TUESDAY` BOOLEAN NOT NULL,
    `IS_WEDNESDAY` BOOLEAN NOT NULL,
    `IS_THURSDAY` BOOLEAN NOT NULL,
    `IS_FRIDAY` BOOLEAN NOT NULL,
    `IS_SATURDAY` BOOLEAN NOT NULL,
    `IS_SUNDAY` BOOLEAN NOT NULL,
    `SEQUENCE` INTEGER NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `menu_category` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `MENU_PROFILE_ID` INTEGER NOT NULL,
    `IMAGE_URL` TEXT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `menu_item` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `ITEM_ID` INTEGER NOT NULL,
    `ITEM_CODE` VARCHAR(191) NOT NULL,
    `IMAGE_URL` TEXT NULL,
    `PRICE` DECIMAL(15, 4) NOT NULL,
    `SEQUENCE` INTEGER NOT NULL,
    `MENU_CATEGORY_ID` INTEGER NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `menu_item_modifier_group` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `MIN_SELECTION` INTEGER NOT NULL,
    `MAX_SELECTION` INTEGER NOT NULL,
    `SEQUENCE` INTEGER NOT NULL,
    `MENU_ITEM_ID` INTEGER NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,
    `FREE_MODIFIER_LIMIT` INTEGER NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `menu_item_modifier` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `ITEM_ID` INTEGER NOT NULL,
    `ITEM_CODE` VARCHAR(191) NOT NULL,
    `IMAGE_URL` TEXT NULL,
    `PRICE` DECIMAL(15, 4) NOT NULL,
    `DEFAULT_SELECTION_QTY` INTEGER NOT NULL,
    `SEQUENCE` INTEGER NOT NULL,
    `MENU_ITEM_MODIFIER_GROUP_ID` INTEGER NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `table` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `OUTLET_ID` INTEGER NOT NULL,
    `TABLE_NUMBER` VARCHAR(191) NOT NULL,
    `CAPACITY` INTEGER NOT NULL,
    `STATUS` VARCHAR(191) NOT NULL,
    `SALES_ID` INTEGER NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `recipe` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `MENU_ITEM_ID` INTEGER NOT NULL,
    `ITEM_ID` INTEGER NOT NULL,
    `QUANTITY` DOUBLE NOT NULL,
    `UNIT` VARCHAR(191) NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,
    `BATCH_YIELD` DOUBLE NULL,
    `MENU_ITEM_MODIFIER_ID` INTEGER NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `station` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `OUTLET_ID` INTEGER NOT NULL,
    `NAME` VARCHAR(191) NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `reservation` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `OUTLET_ID` INTEGER NOT NULL,
    `CUSTOMER_ID` INTEGER NULL,
    `TABLE_ID` INTEGER NULL,
    `DATE_TIME` DATETIME(3) NOT NULL,
    `PARTY_SIZE` INTEGER NOT NULL,
    `STATUS` VARCHAR(191) NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `order_routing` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `SALES_ITEM_ID` INTEGER NOT NULL,
    `STATION_ID` INTEGER NOT NULL,
    `STATUS` VARCHAR(191) NOT NULL,
    `SENT_AT` DATETIME(3) NULL,
    `COMPLETED_AT` DATETIME(3) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `waitlist` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `OUTLET_ID` INTEGER NOT NULL,
    `CUSTOMER_ID` INTEGER NULL,
    `PARTY_SIZE` INTEGER NOT NULL,
    `STATUS` VARCHAR(191) NOT NULL,
    `WAIT_TIME` INTEGER NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `split_bill` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `SALES_ID` INTEGER NOT NULL,
    `AMOUNT` DECIMAL(15, 4) NOT NULL,
    `PAYMENT_ID` INTEGER NULL,
    `CUSTOMER_ID` INTEGER NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `promotion` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `DESCRIPTION` VARCHAR(191) NULL,
    `TYPE` ENUM('DAILY', 'HOURLY', 'GENERIC', 'CUSTOMER') NOT NULL,
    `STATUS` ENUM('ACTIVE', 'INACTIVE', 'EXPIRED', 'SCHEDULED') NOT NULL DEFAULT 'ACTIVE',
    `PRIORITY` INTEGER NOT NULL DEFAULT 1,
    `COMBINATION_RULE` ENUM('STACKABLE', 'EXCLUSIVE') NOT NULL DEFAULT 'STACKABLE',
    `DISCOUNT_TYPE` ENUM('PERCENTAGE', 'FIXED_AMOUNT', 'BUY_X_GET_Y', 'BUY_X_GET_Y_DISCOUNT') NOT NULL,
    `DISCOUNT_VALUE` DECIMAL(65, 30) NULL,
    `BUY_QUANTITY` INTEGER NULL,
    `GET_QUANTITY` INTEGER NULL,
    `GET_DISCOUNT_VALUE` DECIMAL(65, 30) NULL,
    `START_DATE` DATETIME(3) NULL,
    `END_DATE` DATETIME(3) NULL,
    `START_TIME` VARCHAR(191) NULL,
    `END_TIME` VARCHAR(191) NULL,
    `VALID_DAYS` VARCHAR(191) NULL,
    `MIN_PURCHASE_AMOUNT` DECIMAL(65, 30) NULL,
    `MIN_PURCHASE_QTY` INTEGER NULL,
    `MAX_USAGE_TOTAL` INTEGER NULL,
    `MAX_USAGE_PER_CUSTOMER` INTEGER NULL,
    `CURRENT_USAGE` INTEGER NOT NULL DEFAULT 0,
    `IS_CUSTOMER_SPECIFIC` BOOLEAN NOT NULL DEFAULT false,
    `CREATED_BY` VARCHAR(191) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `promotion_item` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PROMOTION_ID` INTEGER NOT NULL,
    `ITEM_ID` INTEGER NULL,
    `CATEGORY_ID` INTEGER NULL,
    `ITEM_CODE` VARCHAR(191) NULL,
    `ITEM_NAME` VARCHAR(191) NULL,
    `ITEM_ROLE` VARCHAR(191) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `promotion_customer` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PROMOTION_ID` INTEGER NOT NULL,
    `CUSTOMER_ID` INTEGER NOT NULL,
    `MAX_USAGE` INTEGER NULL,
    `CURRENT_USAGE` INTEGER NOT NULL DEFAULT 0,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    UNIQUE INDEX `promotion_customer_PROMOTION_ID_CUSTOMER_ID_key`(`PROMOTION_ID`, `CUSTOMER_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `promotion_usage` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PROMOTION_ID` INTEGER NOT NULL,
    `CUSTOMER_ID` INTEGER NULL,
    `SALES_ID` INTEGER NULL,
    `DISCOUNT_AMOUNT` DECIMAL(65, 30) NOT NULL,
    `USED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `VERSION` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `registered_device` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `CLIENT_DEVICE_ID` VARCHAR(191) NOT NULL,
    `SITE_ID` INTEGER NOT NULL,
    `TENANT_ID` INTEGER NOT NULL,
    `DEVICE_NAME` VARCHAR(191) NOT NULL,
    `DEVICE_TYPE` VARCHAR(191) NULL,
    `STATUS` VARCHAR(191) NOT NULL DEFAULT 'active',
    `APP_VERSION` VARCHAR(191) NULL,
    `LAST_SEEN_AT` DATETIME(3) NULL,
    `REGISTERED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    UNIQUE INDEX `registered_device_CLIENT_DEVICE_ID_key`(`CLIENT_DEVICE_ID`),
    INDEX `registered_device_CLIENT_DEVICE_ID_idx`(`CLIENT_DEVICE_ID`),
    INDEX `registered_device_TENANT_ID_idx`(`TENANT_ID`),
    UNIQUE INDEX `registered_device_TENANT_ID_SITE_ID_key`(`TENANT_ID`, `SITE_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `_user_roles` (
    `A` INTEGER NOT NULL,
    `B` INTEGER NOT NULL,

    UNIQUE INDEX `_user_roles_AB_unique`(`A`, `B`),
    INDEX `_user_roles_B_index`(`B`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `role_permission` ADD CONSTRAINT `role_permission_ROLE_ID_fkey` FOREIGN KEY (`ROLE_ID`) REFERENCES `role`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `override_log` ADD CONSTRAINT `override_log_USER_ID_fkey` FOREIGN KEY (`USER_ID`) REFERENCES `user`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `setting` ADD CONSTRAINT `setting_USER_ID_fkey` FOREIGN KEY (`USER_ID`) REFERENCES `user`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `setting` ADD CONSTRAINT `setting_OUTLET_ID_fkey` FOREIGN KEY (`OUTLET_ID`) REFERENCES `outlet`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `item` ADD CONSTRAINT `item_CATEGORY_ID_fkey` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `item_category`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `item` ADD CONSTRAINT `item_SUPPLIER_ID_fkey` FOREIGN KEY (`SUPPLIER_ID`) REFERENCES `supplier`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `sales` ADD CONSTRAINT `sales_CUSTOMER_ID_fkey` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `customer`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `sales` ADD CONSTRAINT `sales_TABLE_ID_fkey` FOREIGN KEY (`TABLE_ID`) REFERENCES `table`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `sales_item` ADD CONSTRAINT `sales_item_SALES_ID_fkey` FOREIGN KEY (`SALES_ID`) REFERENCES `sales`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `sales_item_modifier` ADD CONSTRAINT `sales_item_modifier_MENU_ITEM_MODIFIER_ID_fkey` FOREIGN KEY (`MENU_ITEM_MODIFIER_ID`) REFERENCES `menu_item_modifier`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `sales_item_modifier` ADD CONSTRAINT `sales_item_modifier_SALES_ITEM_ID_fkey` FOREIGN KEY (`SALES_ITEM_ID`) REFERENCES `sales_item`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `sales_quotation_item` ADD CONSTRAINT `sales_quotation_item_SALES_QUOTATION_ID_fkey` FOREIGN KEY (`SALES_QUOTATION_ID`) REFERENCES `sales_quotation`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `invoice` ADD CONSTRAINT `invoice_SESSION_ID_fkey` FOREIGN KEY (`SESSION_ID`) REFERENCES `session`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `invoice` ADD CONSTRAINT `invoice_PURCHASE_ORDER_ID_fkey` FOREIGN KEY (`PURCHASE_ORDER_ID`) REFERENCES `purchase_order`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `invoice` ADD CONSTRAINT `invoice_SUPPLIER_ID_fkey` FOREIGN KEY (`SUPPLIER_ID`) REFERENCES `supplier`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `invoice_item` ADD CONSTRAINT `invoice_item_INVOICE_ID_fkey` FOREIGN KEY (`INVOICE_ID`) REFERENCES `invoice`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `invoice_item` ADD CONSTRAINT `invoice_item_ITEM_ID_fkey` FOREIGN KEY (`ITEM_ID`) REFERENCES `item`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `delivery_order` ADD CONSTRAINT `delivery_order_SESSION_ID_fkey` FOREIGN KEY (`SESSION_ID`) REFERENCES `session`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `delivery_order` ADD CONSTRAINT `delivery_order_PURCHASE_ORDER_ID_fkey` FOREIGN KEY (`PURCHASE_ORDER_ID`) REFERENCES `purchase_order`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `delivery_order` ADD CONSTRAINT `delivery_order_INVOICE_ID_fkey` FOREIGN KEY (`INVOICE_ID`) REFERENCES `invoice`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `delivery_order_item` ADD CONSTRAINT `delivery_order_item_DELIVERY_ORDER_ID_fkey` FOREIGN KEY (`DELIVERY_ORDER_ID`) REFERENCES `delivery_order`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `delivery_order_item` ADD CONSTRAINT `delivery_order_item_ITEM_ID_fkey` FOREIGN KEY (`ITEM_ID`) REFERENCES `item`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `purchase_order` ADD CONSTRAINT `purchase_order_SESSION_ID_fkey` FOREIGN KEY (`SESSION_ID`) REFERENCES `session`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `purchase_order` ADD CONSTRAINT `purchase_order_SUPPLIER_ID_fkey` FOREIGN KEY (`SUPPLIER_ID`) REFERENCES `supplier`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `purchase_order_item` ADD CONSTRAINT `purchase_order_item_PURCHASE_ORDER_ID_fkey` FOREIGN KEY (`PURCHASE_ORDER_ID`) REFERENCES `purchase_order`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `purchase_order_item` ADD CONSTRAINT `purchase_order_item_ITEM_ID_fkey` FOREIGN KEY (`ITEM_ID`) REFERENCES `item`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `payment` ADD CONSTRAINT `payment_SALES_ID_fkey` FOREIGN KEY (`SALES_ID`) REFERENCES `sales`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `register_log` ADD CONSTRAINT `register_log_SALES_ID_fkey` FOREIGN KEY (`SALES_ID`) REFERENCES `sales`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `card_info` ADD CONSTRAINT `card_info_PAYMENT_ID_fkey` FOREIGN KEY (`PAYMENT_ID`) REFERENCES `payment`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `declaration` ADD CONSTRAINT `declaration_SESSION_ID_fkey` FOREIGN KEY (`SESSION_ID`) REFERENCES `session`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `stock_balance` ADD CONSTRAINT `stock_balance_ITEM_ID_fkey` FOREIGN KEY (`ITEM_ID`) REFERENCES `item`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `stock_balance` ADD CONSTRAINT `stock_balance_OUTLET_ID_fkey` FOREIGN KEY (`OUTLET_ID`) REFERENCES `outlet`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `stock_receipt` ADD CONSTRAINT `stock_receipt_ITEM_ID_fkey` FOREIGN KEY (`ITEM_ID`) REFERENCES `item`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `stock_receipt` ADD CONSTRAINT `stock_receipt_OUTLET_ID_fkey` FOREIGN KEY (`OUTLET_ID`) REFERENCES `outlet`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `stock_movement` ADD CONSTRAINT `stock_movement_ITEM_ID_fkey` FOREIGN KEY (`ITEM_ID`) REFERENCES `item`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `stock_movement` ADD CONSTRAINT `stock_movement_OUTLET_ID_fkey` FOREIGN KEY (`OUTLET_ID`) REFERENCES `outlet`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `stock_snapshot` ADD CONSTRAINT `stock_snapshot_ITEM_ID_fkey` FOREIGN KEY (`ITEM_ID`) REFERENCES `item`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `stock_snapshot` ADD CONSTRAINT `stock_snapshot_OUTLET_ID_fkey` FOREIGN KEY (`OUTLET_ID`) REFERENCES `outlet`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `menu_category` ADD CONSTRAINT `menu_category_MENU_PROFILE_ID_fkey` FOREIGN KEY (`MENU_PROFILE_ID`) REFERENCES `menu_profile`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `menu_item` ADD CONSTRAINT `menu_item_MENU_CATEGORY_ID_fkey` FOREIGN KEY (`MENU_CATEGORY_ID`) REFERENCES `menu_category`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `menu_item_modifier_group` ADD CONSTRAINT `menu_item_modifier_group_MENU_ITEM_ID_fkey` FOREIGN KEY (`MENU_ITEM_ID`) REFERENCES `menu_item`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `menu_item_modifier` ADD CONSTRAINT `menu_item_modifier_MENU_ITEM_MODIFIER_GROUP_ID_fkey` FOREIGN KEY (`MENU_ITEM_MODIFIER_GROUP_ID`) REFERENCES `menu_item_modifier_group`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `table` ADD CONSTRAINT `table_OUTLET_ID_fkey` FOREIGN KEY (`OUTLET_ID`) REFERENCES `outlet`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `recipe` ADD CONSTRAINT `recipe_MENU_ITEM_MODIFIER_ID_fkey` FOREIGN KEY (`MENU_ITEM_MODIFIER_ID`) REFERENCES `menu_item_modifier`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `recipe` ADD CONSTRAINT `recipe_MENU_ITEM_ID_fkey` FOREIGN KEY (`MENU_ITEM_ID`) REFERENCES `menu_item`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `recipe` ADD CONSTRAINT `recipe_ITEM_ID_fkey` FOREIGN KEY (`ITEM_ID`) REFERENCES `item`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `station` ADD CONSTRAINT `station_OUTLET_ID_fkey` FOREIGN KEY (`OUTLET_ID`) REFERENCES `outlet`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `reservation` ADD CONSTRAINT `reservation_OUTLET_ID_fkey` FOREIGN KEY (`OUTLET_ID`) REFERENCES `outlet`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `reservation` ADD CONSTRAINT `reservation_CUSTOMER_ID_fkey` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `customer`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `reservation` ADD CONSTRAINT `reservation_TABLE_ID_fkey` FOREIGN KEY (`TABLE_ID`) REFERENCES `table`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `order_routing` ADD CONSTRAINT `order_routing_SALES_ITEM_ID_fkey` FOREIGN KEY (`SALES_ITEM_ID`) REFERENCES `sales_item`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `order_routing` ADD CONSTRAINT `order_routing_STATION_ID_fkey` FOREIGN KEY (`STATION_ID`) REFERENCES `station`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `waitlist` ADD CONSTRAINT `waitlist_OUTLET_ID_fkey` FOREIGN KEY (`OUTLET_ID`) REFERENCES `outlet`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `waitlist` ADD CONSTRAINT `waitlist_CUSTOMER_ID_fkey` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `customer`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `split_bill` ADD CONSTRAINT `split_bill_PAYMENT_ID_fkey` FOREIGN KEY (`PAYMENT_ID`) REFERENCES `payment`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `split_bill` ADD CONSTRAINT `split_bill_CUSTOMER_ID_fkey` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `customer`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `promotion_item` ADD CONSTRAINT `promotion_item_PROMOTION_ID_fkey` FOREIGN KEY (`PROMOTION_ID`) REFERENCES `promotion`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `promotion_customer` ADD CONSTRAINT `promotion_customer_PROMOTION_ID_fkey` FOREIGN KEY (`PROMOTION_ID`) REFERENCES `promotion`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `promotion_customer` ADD CONSTRAINT `promotion_customer_CUSTOMER_ID_fkey` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `customer`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `promotion_usage` ADD CONSTRAINT `promotion_usage_PROMOTION_ID_fkey` FOREIGN KEY (`PROMOTION_ID`) REFERENCES `promotion`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `promotion_usage` ADD CONSTRAINT `promotion_usage_CUSTOMER_ID_fkey` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `customer`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `_user_roles` ADD CONSTRAINT `_user_roles_A_fkey` FOREIGN KEY (`A`) REFERENCES `role`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `_user_roles` ADD CONSTRAINT `_user_roles_B_fkey` FOREIGN KEY (`B`) REFERENCES `user`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
