-- AlterTable
ALTER TABLE `tenant` ADD COLUMN `SLUG` VARCHAR(191) NULL,
    ADD COLUMN `WHATSAPP_NUMBER` VARCHAR(191) NULL,
    ADD COLUMN `CATALOGUE_ENABLED` BOOLEAN NOT NULL DEFAULT false;

-- CreateIndex
CREATE UNIQUE INDEX `tenant_SLUG_key` ON `tenant`(`SLUG`);
