-- AlterTable
ALTER TABLE `item` ADD COLUMN `DEFAULT_LOAD_WEIGHT_KG` DECIMAL(15, 4) NULL;

-- CreateTable
CREATE TABLE `item_consumable` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `SERVICE_ITEM_ID` INTEGER NOT NULL,
    `CONSUMABLE_ITEM_ID` INTEGER NOT NULL,
    `RATE_PER_KG` DECIMAL(15, 4) NOT NULL,
    `UNIT` VARCHAR(191) NOT NULL DEFAULT 'Milliliter',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    INDEX `item_consumable_SERVICE_ITEM_ID_idx`(`SERVICE_ITEM_ID`),
    INDEX `item_consumable_UPDATED_AT_idx`(`UPDATED_AT`),
    UNIQUE INDEX `item_consumable_SERVICE_ITEM_ID_CONSUMABLE_ITEM_ID_key`(`SERVICE_ITEM_ID`, `CONSUMABLE_ITEM_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `item_consumable` ADD CONSTRAINT `item_consumable_SERVICE_ITEM_ID_fkey` FOREIGN KEY (`SERVICE_ITEM_ID`) REFERENCES `item`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `item_consumable` ADD CONSTRAINT `item_consumable_CONSUMABLE_ITEM_ID_fkey` FOREIGN KEY (`CONSUMABLE_ITEM_ID`) REFERENCES `item`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
