-- CreateTable
CREATE TABLE `subscription_plan` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PLAN_NAME` VARCHAR(191) NOT NULL,
    `PLAN_TYPE` VARCHAR(191) NOT NULL DEFAULT 'Retail',
    `PRICE` DOUBLE NOT NULL,
    `MAX_TRANSACTIONS` INTEGER NULL,
    `MAX_PRODUCTS` INTEGER NULL,
    `MAX_USERS` INTEGER NULL,
    `DESCRIPTION` VARCHAR(191) NULL,

    UNIQUE INDEX `subscription_plan_PLAN_NAME_key`(`PLAN_NAME`),
    INDEX `subscription_plan_PRICE_idx`(`PRICE`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `subscription_add_on` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `ADD_ON_TYPE` VARCHAR(191) NOT NULL,
    `PRICE_PER_UNIT` DOUBLE NOT NULL,
    `MAX_QUANTITY` INTEGER NULL,
    `SCOPE` VARCHAR(191) NOT NULL DEFAULT 'outlet',
    `DESCRIPTION` VARCHAR(191) NULL,

    INDEX `subscription_add_on_NAME_idx`(`NAME`),
    INDEX `subscription_add_on_ADD_ON_TYPE_idx`(`ADD_ON_TYPE`),
    INDEX `subscription_add_on_SCOPE_idx`(`SCOPE`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tenant` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TENANT_NAME` VARCHAR(191) NOT NULL,
    `DATABASE_NAME` VARCHAR(191) NULL,
    `PHONE_NUMBER` VARCHAR(191) NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT (UTC_TIMESTAMP()),

    UNIQUE INDEX `tenant_DATABASE_NAME_key`(`DATABASE_NAME`),
    INDEX `tenant_TENANT_NAME_idx`(`TENANT_NAME`),
    INDEX `tenant_CREATED_AT_idx`(`CREATED_AT`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tenant_subscription` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TENANT_ID` INTEGER NOT NULL,
    `OUTLET_ID` INTEGER NOT NULL,
    `SUBSCRIPTION_PLAN_ID` INTEGER NOT NULL,
    `STATUS` VARCHAR(191) NOT NULL DEFAULT 'Active',
    `NEXT_PAYMENT_DATE` DATETIME(3) NOT NULL,
    `SUBSCRIPTION_VALID_UNTIL` DATETIME(3) NOT NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,
    `DISCOUNT_ID` INTEGER NULL,

    INDEX `tenant_subscription_STATUS_idx`(`STATUS`),
    INDEX `tenant_subscription_NEXT_PAYMENT_DATE_idx`(`NEXT_PAYMENT_DATE`),
    INDEX `tenant_subscription_SUBSCRIPTION_VALID_UNTIL_idx`(`SUBSCRIPTION_VALID_UNTIL`),
    INDEX `tenant_subscription_TENANT_ID_STATUS_idx`(`TENANT_ID`, `STATUS`),
    INDEX `tenant_subscription_OUTLET_ID_STATUS_idx`(`OUTLET_ID`, `STATUS`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tenant_subscription_add_on` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TENANT_SUBSCRIPTION_ID` INTEGER NOT NULL,
    `ADD_ON_ID` INTEGER NOT NULL,
    `QUANTITY` INTEGER NOT NULL DEFAULT 0,

    UNIQUE INDEX `tenant_subscription_add_on_TENANT_SUBSCRIPTION_ID_ADD_ON_ID_key`(`TENANT_SUBSCRIPTION_ID`, `ADD_ON_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tenant_outlet` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TENANT_ID` INTEGER NOT NULL,
    `OUTLET_NAME` VARCHAR(191) NOT NULL,
    `ADDRESS` VARCHAR(191) NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `IS_ACTIVE` BOOLEAN NOT NULL DEFAULT true,

    INDEX `tenant_outlet_OUTLET_NAME_idx`(`OUTLET_NAME`),
    INDEX `tenant_outlet_IS_ACTIVE_idx`(`IS_ACTIVE`),
    INDEX `tenant_outlet_TENANT_ID_IS_ACTIVE_idx`(`TENANT_ID`, `IS_ACTIVE`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `discount` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `DISCOUNT_TYPE` VARCHAR(191) NOT NULL,
    `VALUE` DOUBLE NOT NULL,
    `START_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `END_DATE` DATETIME(3) NULL,
    `MAX_USES` INTEGER NULL,
    `APPLIES_TO` VARCHAR(191) NOT NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `discount_NAME_idx`(`NAME`),
    INDEX `discount_DISCOUNT_TYPE_idx`(`DISCOUNT_TYPE`),
    INDEX `discount_START_DATE_END_DATE_idx`(`START_DATE`, `END_DATE`),
    INDEX `discount_APPLIES_TO_idx`(`APPLIES_TO`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tenant_user` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USERNAME` VARCHAR(191) NOT NULL,
    `PASSWORD` VARCHAR(191) NULL,
    `TENANT_ID` INTEGER NOT NULL,
    `ROLE` VARCHAR(191) NOT NULL DEFAULT 'user',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,

    UNIQUE INDEX `tenant_user_USERNAME_key`(`USERNAME`),
    INDEX `tenant_user_ROLE_idx`(`ROLE`),
    INDEX `tenant_user_IS_DELETED_idx`(`IS_DELETED`),
    INDEX `tenant_user_TENANT_ID_ROLE_idx`(`TENANT_ID`, `ROLE`),
    INDEX `tenant_user_TENANT_ID_IS_DELETED_idx`(`TENANT_ID`, `IS_DELETED`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `refresh_token` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TENANT_USER_ID` INTEGER NOT NULL,
    `TOKEN` VARCHAR(191) NOT NULL,
    `EXPIRED_DATETIME` DATETIME(3) NULL,
    `CREATED_DATETIME` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CREATED_BY` VARCHAR(191) NULL,
    `REVOKED_DATETIME` DATETIME(3) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,

    INDEX `refresh_token_TOKEN_idx`(`TOKEN`),
    INDEX `refresh_token_EXPIRED_DATETIME_idx`(`EXPIRED_DATETIME`),
    INDEX `refresh_token_REVOKED_DATETIME_idx`(`REVOKED_DATETIME`),
    INDEX `refresh_token_IS_DELETED_idx`(`IS_DELETED`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `permission` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `CATEGORY` VARCHAR(191) NOT NULL DEFAULT '',
    `DESCRIPTION` VARCHAR(191) NULL,
    `ALLOWED_ROLES` VARCHAR(191) NULL,
    `CREATED_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,
    `DELETED_AT` DATETIME(3) NULL,
    `VERSION` INTEGER NULL DEFAULT 1,

    UNIQUE INDEX `permission_NAME_key`(`NAME`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `tenant_subscription` ADD CONSTRAINT `tenant_subscription_OUTLET_ID_fkey` FOREIGN KEY (`OUTLET_ID`) REFERENCES `tenant_outlet`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `tenant_subscription` ADD CONSTRAINT `tenant_subscription_DISCOUNT_ID_fkey` FOREIGN KEY (`DISCOUNT_ID`) REFERENCES `discount`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `tenant_subscription` ADD CONSTRAINT `tenant_subscription_TENANT_ID_fkey` FOREIGN KEY (`TENANT_ID`) REFERENCES `tenant`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `tenant_subscription` ADD CONSTRAINT `tenant_subscription_SUBSCRIPTION_PLAN_ID_fkey` FOREIGN KEY (`SUBSCRIPTION_PLAN_ID`) REFERENCES `subscription_plan`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `tenant_subscription_add_on` ADD CONSTRAINT `tenant_subscription_add_on_TENANT_SUBSCRIPTION_ID_fkey` FOREIGN KEY (`TENANT_SUBSCRIPTION_ID`) REFERENCES `tenant_subscription`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `tenant_subscription_add_on` ADD CONSTRAINT `tenant_subscription_add_on_ADD_ON_ID_fkey` FOREIGN KEY (`ADD_ON_ID`) REFERENCES `subscription_add_on`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `tenant_outlet` ADD CONSTRAINT `tenant_outlet_TENANT_ID_fkey` FOREIGN KEY (`TENANT_ID`) REFERENCES `tenant`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `tenant_user` ADD CONSTRAINT `tenant_user_TENANT_ID_fkey` FOREIGN KEY (`TENANT_ID`) REFERENCES `tenant`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
