-- CreateTable
CREATE TABLE `UNKNOWN` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CREATED_DATETIME` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `STRING_EXTEND_1` VARCHAR(191) NOT NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
