-- CreateTable
CREATE TABLE `notification_preference` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USER_ID` INTEGER NOT NULL,
    `SALES_NOTIFICATIONS` BOOLEAN NOT NULL DEFAULT true,
    `INVENTORY_ALERTS` BOOLEAN NOT NULL DEFAULT true,
    `ORDER_UPDATES` BOOLEAN NOT NULL DEFAULT true,
    `SYSTEM_ALERTS` BOOLEAN NOT NULL DEFAULT true,
    `FINANCIAL_NOTIFICATIONS` BOOLEAN NOT NULL DEFAULT true,
    `STAFF_NOTIFICATIONS` BOOLEAN NOT NULL DEFAULT true,
    `QUIET_HOURS_START` VARCHAR(191) NULL,
    `QUIET_HOURS_END` VARCHAR(191) NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    UNIQUE INDEX `notification_preference_USER_ID_key`(`USER_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `notification_preference` ADD CONSTRAINT `notification_preference_USER_ID_fkey` FOREIGN KEY (`USER_ID`) REFERENCES `user`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
